name: 'Install Cache'

description: 'Read / write install cache'

runs:
  using: 'composite'
  steps:
    - uses: ukhsa-internal/restore-virtualenv@main
      id: cache-virtualenv

    - uses: ukhsa-internal/restore-pip-download-cache@main
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt --no-cache-dir
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      shell: bash
