name: 'Install Cache'

description: 'Read / write install cache'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        pip install -r requirements.txt --no-cache-dir
      shell: bash
