name: 'Install Cache'

description: 'Read / write install cache'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
    - name: Cache dependencies
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
      id: cache
      # Using the native `setup-python` `cache` interface only caches dependencies
      # as opposed to the build itself.
      # So even with dependencies cached, there is still a +1min penalty to pay
      # With this we cache the build and so that each CI job can get straight into what it wants to do
      with:
        path: .venv
        key: venv-${{ hashFiles('requirements-prod.txt') }}-${{ hashFiles('requirements-dev.txt') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        source uhd.sh
        uhd venv create
      shell: bash
