name: 'Install Cache'

description: 'Read / write install cache'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      # Using the native `setup-python` `cache` interface only caches dependencies
      # as opposed to the build itself.
      # So even with dependencies cached, there is still a +1min penalty to pay
      # With this we cache the build and so that each CI job can get straight into what it wants to do
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements-prod.txt') }}-${{ hashFiles('requirements-dev.txt') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt
      shell: bash
