name: 'Install Cache'

description: 'Read / write install cache'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit == 'false'
      run: pip install -r requirements.txt
      shell: bash
