# Generated by Django 5.1.5 on 2025-01-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data", "0033_remove_rounding_column_from_metric_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiPermission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "age",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_permissions",
                        to="data.age",
                    ),
                ),
                (
                    "geography",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geography_permissions",
                        to="data.geography",
                    ),
                ),
                (
                    "geography_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geography_type_permissions",
                        to="data.geographytype",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_permissions",
                        to="data.metric",
                    ),
                ),
                (
                    "stratum",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stratum_permissions",
                        to="data.stratum",
                    ),
                ),
                (
                    "sub_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_theme_permissions",
                        to="data.subtheme",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_permissions",
                        to="data.theme",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_permissions",
                        to="data.topic",
                    ),
                ),
            ],
            options={
                "db_table": "api_permissions",
                "unique_together": {
                    (
                        "theme",
                        "sub_theme",
                        "topic",
                        "metric",
                        "geography_type",
                        "geography",
                        "age",
                        "stratum",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="ApiGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        related_name="api_groups", to="api.apipermission"
                    ),
                ),
            ],
            options={
                "db_table": "api_groups",
            },
        ),
    ]
