# Generated by Django 5.1.5 on 2025-01-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatasetGroup",
            fields=[
                ("group_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "dataset_groups",
            },
        ),
        migrations.CreateModel(
            name="DatasetGroupMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dataset_name", models.CharField(max_length=255)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_mappings",
                        to="api.datasetgroup",
                    ),
                ),
            ],
            options={
                "db_table": "dataset_group_mappings",
                "unique_together": {("dataset_name", "group")},
            },
        ),
    ]
