FROM public.ecr.aws/lambda/python:3.11

# Ensure the virtual environment will be available on the `PATH` variable
ENV PATH=/venv/bin:$PATH

# Copy the production-only dependencies into place for the ingestion component
COPY requirements-prod-ingestion.txt requirements-prod-ingestion.txt

# Main build process
RUN pip install --upgrade pip \
    # Upgrade the pip installer to the latest version \
    && pip install -r requirements-prod-ingestion.txt
    # Install project dependencies for the ingestion component

# Mounts the application code into the image
COPY . ${LAMBDA_TASK_ROOT}

## Sets the working directory for subsequent `RUN`, `ENTRYPOINT` & `CMD` layers
WORKDIR ${LAMBDA_TASK_ROOT}

## Ensure the virtual environment is made available on the system `PATH`
ENV PATH=/venv/bin:$PATH

# Listen on the specified port at runtime
# Note that this does not actually publish the port.
# This also assumes TCP.
EXPOSE 8000

# Runs the lambda entrypoint by default
CMD ["ingestion.operations.lambda_entrypoint.handler"]