########################################################################################################################
# Ruff configuration
########################################################################################################################
[tool.ruff]
select = [
    "C90",      # mccabe
    "E",        # pycodestyle
    "W",        # pycodestyle
    "F",        # Pyflakes
    "N",        # pep8-naming
    "ASYNC",    # flake8-async
    "S",        # flake8-bandit
    "BLE",      # flake8-blind-except
    "A",        # flake8-builtins
    "C4",       # flake8-comprehensions
    "T10",      # flake8-debugger
    "EXE",      # flake8-executable
    "FA",       # flake8-future-annotations
    "ISC",      # flake8-implicit-str-concat
    "ICN",      # flake8-import-conventions
    "G",        # flake8-logging-format
    "T20",      # flake8-print
    "PYI",      # flake8-pyi
    "Q",        # flake8-quotes
    "YTT",      # flake8-2020
    "SLOT",     # flake8-slots
    "TID",      # flake8-tidy-imports
    "INT",      # flake8-gettext
    "PIE",      # flake8-pie
    "TD",       # flake8-todos
    "FIX",      # flake8-fixme
    "RSE",      # flake8-raise
    "RET",      # flake8-return
    "SLF",      # flake8-self
    "SIM",      # flake8-simplify
    "PERF",     # Perflint
    "ERA",      # eradicate
    "PGH",      # pygrep-hooks
    "FLY",      # flynt
    "AIR",      # airflow
    "FURB",     # refurb
    "I",        # isort
    "TRY",      # tryceratops
    "UP",       # pyupgrade
]

# Ignore rules
ignore = [
    "F821"      # Undefined class names - currently used to bypass circular imports in type hints
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".ruff_cache",
    "venv",
    ".venv",
    "__pypackages__",
    "build",
    "dist",
    "*/migrations/*",
    "*/__init__.py",
]

# Allow line lengths of up to 120 characters
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11
target-version = "py311"

[tool.ruff.per-file-ignores]
"**/{tests}/*"                  = [
                                    "E501",               # Ignore line length in test files
                                    "S101",               # Ignore use of `assert` statement in tests
                                    "SLF001"              # Ignore access of private methods/attributes in tests
                                  ]
"metrics/api/views/*"           = ["E501"]                # Ignore line length in API views.
                                                          # This infringement is due to
                                                          # swagger-facing docstrings/documentation
"metrics/api/views/charts.py"   = ["SIM115"]              # Ignore context handler for opening file
"**/waffle/pre_processing.py"   = ["E203"]                # Ignore whitespace before `:` conflicting with Black
"**/help_texts.py"              = ["W291"]                # Ignore trailing whitespace for help texts
"**/build_cms_site.py"          = ["W605"]                # Ignore escape sequences used in regex calls
"ingestion/file_ingestion.py"   = ["BLE001"]              # Ignore blind exception catch for file ingestion function
"ingestion/reader.py"           = ["SIM105"]              # Ignore request for `contextlib.supress()`
"public_api/views/root_view.py" = ["A002"]                # Ignore built-in `format` used in arg to extended
                                                          # rest framework API view method
"caching/public_api/crawler.py" = ["PERF401"]             # Ignore list comprehension which would reduce readibility
"manage.py"                     = ["TRY003"]              # Ignore long message on exception from Django boilerplate

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

########################################################################################################################
# Pytest configuration
########################################################################################################################
[tool.pytest.ini_options]
# This is needed to point pytest at the settings.py file for the django app
DJANGO_SETTINGS_MODULE = "metrics.api.settings"
addopts = "--random-order"

########################################################################################################################
# Bandit configuration
########################################################################################################################
[bandit]
exclude = ["/tests"]

########################################################################################################################
# Import linter configuration
########################################################################################################################
[tool.importlinter]
# This is needed to point pytest at the settings.py file for the django app
root_packages = [
    "cms",
    "metrics",
    "public_api",
    "feedback",
    "ingestion",
    "tests",
]
include_external_packages = true

[[tool.importlinter.contracts]]
name = "Metrics and CMS do not depend on each other, except via the designated interface and connection of URLs."
type = "independence"
modules = [
    "metrics",
    "cms",
]
ignore_imports = [
    "cms.metrics_interface.interface -> metrics.data.models.core_models",
    "cms.metrics_interface.interface -> metrics.domain.utils",
    "cms.metrics_interface.interface -> metrics.domain.charts.line_multi_coloured.properties",
    "cms.metrics_interface.interface -> metrics.domain.charts.colour_scheme",
    "metrics.api.urls_construction -> cms.dashboard.viewsets",
]

[[tool.importlinter.contracts]]
name = "Metrics package enforces clear architectural layers within itself."
type = "layers"
layers = [
    "metrics.api",
    "metrics.domain",
    "metrics.data",
]
#----------------------------------------------- Public API contracts -------------------------------------------------#
[[tool.importlinter.contracts]]
name = "Public API only depends on the APITimeSeries model & corresponding components via the designated interface."
type = "forbidden"
source_modules = [
    "public_api",
]
forbidden_modules = [
    "metrics.api",
    "metrics.data",
    "metrics.domain",
    "metrics.interfaces",
    "cms",
    "ingestion",
    "feedback",
]
ignore_imports = [
    "public_api.metrics_interface.interface -> metrics.data.models.api_models",
]

[[tool.importlinter.contracts]]
name = "The Public API module is only imported for the wiring of URLs."
type = "forbidden"
source_modules = [
    "metrics.api",
    "metrics.data",
    "metrics.domain",
    "metrics.interfaces",
    "cms",
    "ingestion",
    "feedback",
]
forbidden_modules = [
    "metrics.public_api",
]
ignore_imports = [
    "metrics.api.urls_construction -> public_api",
]
#----------------------------------------------- Ingestion contracts --------------------------------------------------#
[[tool.importlinter.contracts]]
name = "The Ingestion module only depends on the core models & associated components via the designated interface"
type = "forbidden"
source_modules = [
    "ingestion",
]
forbidden_modules = [
    "metrics.api",
    "metrics.data",
    "metrics.domain",
    "metrics.interfaces",
    "cms",
    "feedback",
    "public_api",
]
ignore_imports = [
    "ingestion.metrics_interfaces.interface -> metrics.data.models.core_models",
    "ingestion.metrics_interfaces.interface -> metrics.data.models.api_models",
    "ingestion.metrics_interfaces.interface -> metrics.data.enums",
    "ingestion.operations.api_models -> metrics.data.models.api_models",
    "ingestion.operations.truncated_dataset -> metrics.api.settings",
]
#------------------------------------------ Metrics Domain library contracts ------------------------------------------#
[[tool.importlinter.contracts]]
name = "Metrics charts library does not depend on the rest of the codebase"
type = "forbidden"
source_modules = [
    "metrics.domain.charts",
]
forbidden_modules = [
    "metrics.api",
    "metrics.data",
    "metrics.interfaces",
    "cms",
    "ingestion",
    "feedback",
    "public_api",
]

[[tool.importlinter.contracts]]
name = "Metrics trends library does not depend on the rest of the codebase"
type = "forbidden"
source_modules = [
    "metrics.domain.trends",
]
forbidden_modules = [
    "metrics.api",
    "metrics.data",
    "metrics.interfaces",
    "cms",
    "ingestion",
    "feedback",
    "public_api",
]
#------------------------------------------- Feedback module contracts ------------------------------------------------#
[[tool.importlinter.contracts]]
name = "Feedback module does not depend on the rest of the codebase"
type = "forbidden"
source_modules = [
    "feedback",
]
forbidden_modules = [
    "cms",
    "metrics",
    "public_api",
    "ingestion",
]

[[tool.importlinter.contracts]]
name = "The rest of the codebase does not depend on the feedback module except for the connection of URLs"
type = "forbidden"
source_modules = [
    "cms",
    "metrics",
    "public_api",
    "ingestion",
]
forbidden_modules = [
    "feedback",
]
ignore_imports = [
    "metrics.api.urls_construction -> feedback.api.urls",
]
#------------------------------------------ Source/Test code contracts ------------------------------------------------#
[[tool.importlinter.contracts]]
name = "Source code does not depend on test code"
type = "forbidden"
source_modules = [
    "cms",
    "metrics",
    "public_api",
    "ingestion",
    "feedback",
]
forbidden_modules = [
    "tests",
]
