name: 'Publish image to AWS ECR'

description: 'Builds, tags and pushes a Docker image to AWS ECR'

inputs:
  ecr-repository:
    description: 'The name of the Amazon ECR repository to push the image to.'
    required: true
  build-command:
    description: 'The command for building the Docker image.'
    required: true
  role-to-assume:
    description: 'The role to assume when publishing the image'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to AWS ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        IMAGE_TAG: latest
      run: |
          ${{ inputs.build-command }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      shell: bash
