name: 'Publish image to ECR'

description: 'Builds, tags, and pushes Docker image to Amazon ECR'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::518944279943:role/devops_github_actions_wp_api
        role-session-name: testsession
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecrRepository }}
        IMAGE_TAG: latest
      run: |
          ${{ inputs.buildCommand }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      shell: bash

inputs:
  ecrRepository:
    description: 'The name of the Amazon ECR repository to push the image to'
    required: true

  buildCommand:
    description: 'The command for building the Docker image'
    required: true
