# Generated by Django 4.1.7 on 2023-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicpagerelatedlink",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
    ]
