# Generated by Django 4.2.7 on 2024-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0006_add_geography_sex_age_stratum_to_base_metrics_topicpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="enable_area_selector",
            field=models.BooleanField(default=False),
        ),
    ]
