# Generated by Django 5.2.9 on 2026-01-22 11:56

import cms.metrics_interface.field_choices_callables
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0021_add_dual_category_chart_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="enable public page"),
            preserve_default=False,
        )
    ]
