# Generated by Django 5.1.7 on 2025-04-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0021_alter_commonpageannouncement_banner_type_and_more"),
        ("whats_new", "0009_alter_whatsnewchildentryannouncement_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CommonPageAnnouncement",
            new_name="TopicPageAnnouncement",
        ),
        migrations.AlterModelOptions(
            name="topicpageannouncement",
            options={},
        ),
    ]
