# Generated by Django 5.1.7 on 2025-04-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0022_rename_commonpageannouncement_topicpageannouncement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topicpageannouncement",
            name="badge",
        ),
    ]
