# Generated by Django 5.2.9 on 2026-01-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0022_topicpage_enable_public_page_alter_topicpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicpage",
            name="enable_public_page",
            field=models.BooleanField(default=False),
        ),
    ]
