# Generated by Django 5.2.9 on 2026-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0022_alter_topicpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="enable public page"),
            preserve_default=False,
        ),
    ]
