# Generated by Django 5.1.7 on 2025-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0023_remove_topicpageannouncement_badge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topicpageannouncement",
            options={"base_manager_name": "objects"},
        ),
    ]
