# Generated by Django 5.2.9 on 2026-01-27 12:52

import cms.metrics_interface.field_choices_callables
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0023_alter_topicpage_add_confidence_intervals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 145)],
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nThe text you add here will be used as the heading for this section. \n",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h2", "h3", "h4", "bold", "ul", "link"],
                            "help_text": "\nThis section of text will comprise this card. \nNote that this card will span the length of the available page width if sufficient text content is provided.\n",
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("body", 1)]], {}),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nThe title to display for this component. \nNote that this will be shown in the hex colour #505A5F\n",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nAn optional body of text to accompany this block. This text will be displayed below the chart title.\n",
                            "label": "Subtitle",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "\nAn optional body of text to accompany this block. This text will be displayed in the about content of the chart.\n",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nThe Text that will be displayed for the URL.\n",
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nThe URL that the user will be navigated to when clicked.\nAn optional body of text to accompany this block. This text will be displayed below the chart title.\n",
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("link_display_text", 6), ("link", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_link", 8)]],
                        {
                            "help_text": "\nProvide optional URLs that can provide further contextual information for the data displayed in the chart.\n",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nThe ID to associate with this component. \nThis allows for tracking of events when users interact with this component.\nNote that changing this multiple times will result in the recording of different groups of events.\n",
                            "label": "Tag manager event ID",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                            "help_text": "\nAn optional choice of what to display along the x-axis of the chart.\nIf nothing is provided, `dates` will be used by default.\nDates are used by default\n",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "\nAn optional title to display along the x-axis of the chart.\nIf nothing is provided, then no title will be displayed.\n",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                            "help_text": "\nAn optional choice of what to display along the y-axis of the chart.\nIf nothing is provided, `metric value` will be used by default.\n",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "\nAn optional title to display along the y-axis of the chart.\nIf nothing is provided, then no title will be displayed.\n",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {
                            "default": 0,
                            "help_text": "\nThis field allows you to set the first value in the chart's y-axis range. Please\nnote that a value provided here, which is higher than the lowest value in the data will\nbe overridden and the value from the dataset will be used.\n",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {
                            "help_text": "\nThis field allows you to set the last value in the chart's y-axis range. Please\nnote that a value provided here, which is lower than the highest value in the data will\nbe overridden and the value from the dataset will be used. \n",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "\nThis is a switch to show tooltips on hover within the chart.\nDefaults to False.\n",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Up to and including",
                            "help_text": "\nThis is the accompanying text for chart dates Eg: `Up to and including` 21 Oct 2024\n",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "\nThis option enables timeseries filter for this chart.\nThe timeseries filter allows a user to change the timeseries range for example between\n1m, 3m, 6m, 1y etc.\n",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_topic_names,
                            "help_text": "The name of the topic to pull data e.g. COVID-19.",
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_timeseries_metric_names,
                            "help_text": '\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_geography_names,
                            "help_text": "\nThe name of the geography associated with this particular piece of data.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                        },
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_geography_type_names,
                            "help_text": "\nThe type of geographical categorisation to apply any data filtering to.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                        },
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_sex_names,
                            "help_text": "\nThe gender to filter for, if any.\nThe only options available are `M`, `F` and `ALL`.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n",
                        },
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_age_names,
                            "help_text": "\nThe age band to filter for, if any.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n",
                        },
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_stratum_names,
                            "help_text": "\nThe smallest subgroup a piece of data can be broken down into.\nFor example, this could be broken down by ethnicity or testing pillar.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                        },
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_chart_types,
                            "help_text": "\nThe name of the type of chart which you want to create e.g. bar\n",
                        },
                    ),
                    28: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "\nThe date from which to begin the supporting plot data. \nNote that if nothing is provided, a default of 1 year ago from the current date will be applied.\n",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "\nThe date to which to end the supporting plot data. \nNote that if nothing is provided, a default of the current date will be applied.\n",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nThe label to assign on the legend for this individual plot.\nE.g. `15 to 44 years old`\n",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_colours,
                            "help_text": '\nThe colour to apply to this individual line plot. The colours conform to the GDS specification.\nCurrently, only the `line_multi_coloured` chart type supports different line colours.\nFor all other chart types, this field will be ignored.\nNote that if nothing is provided, a default of "BLACK" will be applied.\nE.g. `GREEN`\n',
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_chart_line_types,
                            "help_text": '\nThe line type to apply to this individual line plot.\nCurrently, only the `line_multi_coloured` chart type supports different line types.\nFor all other chart types, this field will be ignored.\nNote that if nothing is provided, a default of "SOLID" will be applied.\nE.g. `DASH`\n',
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "\nIf set to true, markers are drawn on each individual data point.\nIf set to false, markers are not drawn at all.\nThis is only applicable to line-type charts.\n",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "\nIf set to true, draws the plot as a spline line, resulting in smooth curves between data points.\nIf set to false, draws the plot as a linear line, \nresulting in linear point-to-point lines being drawn between data points.\nThis is only applicable to line-type charts.\n",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("topic", 20),
                                ("metric", 21),
                                ("geography", 22),
                                ("geography_type", 23),
                                ("sex", 24),
                                ("age", 25),
                                ("stratum", 26),
                                ("chart_type", 27),
                                ("date_from", 28),
                                ("date_to", 29),
                                ("label", 30),
                                ("line_colour", 31),
                                ("line_type", 32),
                                ("use_markers", 33),
                                ("use_smooth_lines", 34),
                            ]
                        ],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.StreamBlock",
                        [[("plot", 35)]],
                        {
                            "help_text": "\nAdd the plots required for your chart. \nWithin each plot, you will be required to add a set of fields which will be used to fetch the supporting data \nfor that plot.\n"
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("body", 4),
                                ("about", 5),
                                ("related_links", 9),
                                ("tag_manager_event_id", 10),
                                ("x_axis", 11),
                                ("x_axis_title", 12),
                                ("y_axis", 13),
                                ("y_axis_title", 14),
                                ("y_axis_minimum_value", 15),
                                ("y_axis_maximum_value", 16),
                                ("show_tooltips", 17),
                                ("date_prefix", 18),
                                ("show_timeseries_filter", 19),
                                ("chart", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                            "help_text": "\nA required choice of what to display along the x-axis of the chart.\n",
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_headline_metric_names,
                            "help_text": '\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_headline_chart_types,
                            "help_text": "\nThe name of the type of chart which you want to create e.g. bar\n",
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("topic", 20),
                                ("metric", 39),
                                ("geography", 22),
                                ("geography_type", 23),
                                ("sex", 24),
                                ("age", 25),
                                ("stratum", 26),
                                ("chart_type", 40),
                                ("line_colour", 31),
                                ("label", 30),
                            ]
                        ],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.StreamBlock",
                        [[("plot", 41)]],
                        {
                            "help_texts": "\nAdd the plots required for your chart. \nWithin each plot, you will be required to add a set of fields which will be used to fetch the supporting data \nfor that plot.\n"
                        },
                    ),
                    43: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "\nToggle to enable confidence intervals if they are present in the data set\n",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Metric column includes 95% lower and upper confidence intervals, in brackets.",
                            "help_text": "\nAn optional body of text to accompany this block.\nThis text will be displayed above the metrics table if confidence intervals is enabled.\n",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_colours,
                            "help_text": '\nThe colour to display the confidence interval in. The colours conform to the GDS specification.\nNote that if nothing is provided, a default of "BLACK" will be applied.\n',
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("body", 4),
                                ("about", 5),
                                ("related_links", 9),
                                ("tag_manager_event_id", 10),
                                ("x_axis", 38),
                                ("x_axis_title", 12),
                                ("y_axis", 13),
                                ("y_axis_title", 14),
                                ("y_axis_minimum_value", 15),
                                ("y_axis_maximum_value", 16),
                                ("show_tooltips", 17),
                                ("date_prefix", 18),
                                ("show_timeseries_filter", 19),
                                ("chart", 42),
                                ("confidence_intervals", 43),
                                ("confidence_intervals_description", 44),
                                ("confidence_colour", 45),
                            ]
                        ],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nAn optional body of text to accompany this block. This text will be displayed in the about content of the chart.\n",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_unique_metric_names,
                            "help_text": '\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                        },
                    ),
                    49: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nAn optional body of text to accompany this block. This text will be displayed below the chart title.\n",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("topic", 20),
                                ("metric", 48),
                                ("geography", 22),
                                ("geography_type", 23),
                                ("sex", 24),
                                ("age", 25),
                                ("stratum", 26),
                                ("body", 49),
                            ]
                        ],
                        {
                            "help_text": '\nThis component will display a key headline number type metric.\nYou can also optionally add a body of text to accompany that headline number.\nE.g. "Patients admitted"\n'
                        },
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_unique_change_type_metric_names,
                            "help_text": "\nThe name of the trend type metric to pull data e.g. \"COVID-19_headline_ONSdeaths_7daychange\". \nNote that only 'change' type metrics are available for selection for this field type.\n",
                        },
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_unique_percent_change_type_names,
                            "help_text": "\nThe name of the accompanying percentage trend type metric to pull data \ne.g. \"COVID-19_headline_ONSdeaths_7daypercentchange\". \nNote that only 'percent' type metrics are available for selection for this field type.\n",
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("topic", 20),
                                ("metric", 51),
                                ("geography", 22),
                                ("geography_type", 23),
                                ("sex", 24),
                                ("age", 25),
                                ("stratum", 26),
                                ("body", 49),
                                ("percentage_metric", 52),
                            ]
                        ],
                        {
                            "help_text": '\nThis component will display a trend number type metric.\nThis will display an arrow pointing in the direction of the metric change \nas well as colouring of the block to indicate the context of the change.\nYou can also optionally add a body of text to accompany that headline number.\nE.g. "Last 7 days"\n'
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("topic", 20),
                                ("metric", 48),
                                ("geography", 22),
                                ("geography_type", 23),
                                ("sex", 24),
                                ("age", 25),
                                ("stratum", 26),
                                ("body", 49),
                            ]
                        ],
                        {
                            "help_text": '\nThis component will display a percentage number type metric.\nThis will display the value of the metric appended with a % character.\nYou can also optionally add a body of text to accompany this percentage number.\nE.g. "Virus tests positivity".\n'
                        },
                    ),
                    55: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("headline_number", 50),
                                ("trend_number", 53),
                                ("percentage_number", 54),
                            ]
                        ],
                        {
                            "help_text": "\nAdd up to 2 headline or trend number column components within this space.\nNote that these figures will be displayed within the card, and above the chart itself.\n",
                            "max_num": 2,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("body", 4),
                                ("about", 47),
                                ("related_links", 9),
                                ("tag_manager_event_id", 10),
                                ("x_axis", 11),
                                ("x_axis_title", 12),
                                ("y_axis", 13),
                                ("y_axis_title", 14),
                                ("y_axis_minimum_value", 15),
                                ("y_axis_maximum_value", 16),
                                ("show_tooltips", 17),
                                ("date_prefix", 18),
                                ("show_timeseries_filter", 19),
                                ("chart", 36),
                                ("headline_number_columns", 55),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nThe sub title to display for this component.\n",
                            "required": False,
                        },
                    ),
                    58: (
                        "cms.dynamic_content.blocks.PageLinkChooserBlock",
                        (),
                        {
                            "help_text": "\nThe related topic page you want to link to. Eg: `COVID-19`\n",
                            "page_type": ["topic.TopicPage"],
                            "required": True,
                        },
                    ),
                    59: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                            "help_text": "\nA required choice of what to display along the x-axis of the chart.\n",
                            "ready_only": True,
                        },
                    ),
                    60: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                            "help_text": "\nA required choice of what to display along the y-axis of the chart.\n",
                        },
                    ),
                    61: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_simplified_chart_types
                        },
                    ),
                    62: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "\nIf set to true, draws the plot as a spline line, resulting in smooth curves between data points.\nIf set to false, draws the plot as a linear line, \nresulting in linear point-to-point lines being drawn between data points.\nThis is only applicable to line-type charts.\n",
                            "required": False,
                        },
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("topic", 20),
                                ("metric", 21),
                                ("geography", 22),
                                ("geography_type", 23),
                                ("sex", 24),
                                ("age", 25),
                                ("stratum", 26),
                                ("chart_type", 61),
                                ("date_from", 28),
                                ("date_to", 29),
                                ("use_smooth_lines", 62),
                            ]
                        ],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.StreamBlock",
                        [[("plot", 63)]],
                        {
                            "help_text": "\nAdd the plots required for your chart. \nWithin each plot, you will be required to add a set of fields which will be used to fetch the supporting data \nfor that plot.\n",
                            "max_num": 1,
                            "required": True,
                        },
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("sub_title", 57),
                                ("tag_manager_event_id", 10),
                                ("topic_page", 58),
                                ("x_axis", 59),
                                ("x_axis_title", 12),
                                ("y_axis", 60),
                                ("y_axis_title", 14),
                                ("y_axis_minimum_value", 15),
                                ("y_axis_maximum_value", 16),
                                ("chart", 64),
                            ]
                        ],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                            "help_text": "\nAn optional choice of what to display along the x-axis of the chart.\nIf nothing is provided, `dates` will be used by default.\nDates are used by default\n",
                        },
                    ),
                    67: (
                        "wagtail.blocks.MultipleChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_subcategory_choices,
                            "help_text": "\nSelect a list of primary field values for the chart, these will be you're x-axis.\nFor example if we're creating a stacked bar chart that has a metric value in y and geographies along\nthe x-axis. The `primary field values` should be the list of geographies to include in the chart.\n",
                            "required": False,
                        },
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                            "help_text": "\nAn optional choice of what to display along the y-axis of the chart.\nIf nothing is provided, `metric value` will be used by default.\n",
                        },
                    ),
                    69: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_dual_category_chart_types,
                            "help_text": "\nThe name of the type of chart which you want to create e.g. bar\n",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("topic", 20),
                                ("metric", 48),
                                ("geography", 22),
                                ("geography_type", 23),
                                ("sex", 24),
                                ("age", 25),
                                ("stratum", 26),
                                ("date_from", 28),
                                ("date_to", 29),
                            ]
                        ],
                        {},
                    ),
                    71: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_dual_chart_secondary_category_choices,
                            "help_text": "\nThis is for selecting the Second categorical variable type for Dual category charts.\nFor example when building a `Stacked bar chart` where the x-axis may be of type `Sex` and\ndisplay `Male` and `Female` along the x-axis. If our stacked bar chart then breaks each bar up into\nage groups, then our `Secondary Category` type is `Age`.\n",
                        },
                    ),
                    72: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_subcategory_choices,
                            "help_text": "\nSelect the secondary field for a `Segments` this is the second categorical variable used to create segments\nof a `stacked bar` chart. For example if we're creating a stacked bar chart that has a metric in the y-axis\nand geographies along the x-axis. If each bar is broken into segments by `age group` this field\nshould be the age group for this segment.\n",
                        },
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("secondary_field_value", 72),
                                ("colour", 31),
                                ("label", 30),
                            ]
                        ],
                        {},
                    ),
                    74: (
                        "wagtail.blocks.StreamBlock",
                        [[("segment", 73)]],
                        {"min_num": 1},
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("body", 4),
                                ("about", 5),
                                ("related_links", 9),
                                ("tag_manager_event_id", 10),
                                ("x_axis", 66),
                                ("x_axis_title", 12),
                                ("primary_field_values", 67),
                                ("y_axis", 68),
                                ("y_axis_title", 14),
                                ("y_axis_minimum_value", 15),
                                ("y_axis_maximum_value", 16),
                                ("chart_type", 69),
                                ("static_fields", 70),
                                ("second_category", 71),
                                ("segments", 74),
                            ]
                        ],
                        {},
                    ),
                    76: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("chart_card", 37),
                                ("headline_chart_card", 46),
                                ("chart_with_headline_and_trend_card", 56),
                                ("simplified_chart_with_link", 65),
                                ("dual_category_chart_card", 75),
                            ]
                        ],
                        {
                            "help_text": "\nHere you can add 1 or 2 columns to contain a particular chart card.\nIf you add the 1 column, then the chart card will spread across the available width.\nIf you add 2 columns, then the cards will be split across 2 columns within the available width.\n",
                            "max_num": 2,
                            "min_num": 1,
                        },
                    ),
                    77: ("wagtail.blocks.StructBlock", [[("columns", 76)]], {}),
                    78: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Up to",
                            "help_text": "\nThis is the accompanying text for headline column dates Eg: `Up to` 27 Oct 2024 \n",
                            "required": True,
                        },
                    ),
                    79: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("headline_number", 50),
                                ("trend_number", 53),
                                ("percentage_number", 54),
                            ]
                        ],
                        {
                            "help_text": "\nHere you can add up to 2 rows within this column component.\nEach row can be used to add a number block. \nThis can be a headline number, a trend number or a percentage number.\nIf you only add 1 row, then that block will be rendered on the upper half of the column.\nAnd the bottom row of the column will remain empty.\n",
                            "max_num": 2,
                            "min_num": 1,
                            "required": True,
                        },
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("date_prefix", 78), ("rows", 79)]],
                        {},
                    ),
                    81: (
                        "wagtail.blocks.StreamBlock",
                        [[("column", 80)]],
                        {
                            "help_text": "\nAdd up to 5 number column components within this row. \nThe columns are ordered from left to right, top to bottom respectively. \nSo by moving 1 column component above the other, that component will be rendered in the column left of the other. \n",
                            "max_num": 5,
                            "min_num": 1,
                        },
                    ),
                    82: ("wagtail.blocks.StructBlock", [[("columns", 81)]], {}),
                    83: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    84: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "\nThis field is used to provide a start date for the current time range option. Its date\nmust be earlier than the date provided for the corresponding `date_to`field. \n",
                            "required": True,
                        },
                    ),
                    85: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {
                            "help_text": "\nThis field is used to provide an end date for the current time range option. Its date\nmust be later than the date provided in the corresponding `date_from` field.\n",
                            "required": True,
                        },
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 83), ("date_from", 84), ("date_to", 85)]],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.StreamBlock",
                        [[("time_period", 86)]],
                        {
                            "help_text": "\nThis mandatory time range is used to set the time range that a user can navigate through when\ninteracting with a filter linked chart or map card. Eg. Year selection can include a range of\nyears as dates that can be displayed and navigated between.\nWhen entering multiple periods in the time filter each proceeding `date_from` must be 1 day after the `date_to` \nthat came before it to maintain sequence order.\n",
                            "min_num": 1,
                        },
                    ),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 83), ("time_periods", 87)]],
                        {
                            "help_text": "\nThis mandatory time range is used to set the time range that a user can navigate through when\ninteracting with a filter linked chart or map card. Eg. Year selection can include a range of\nyears as dates that can be displayed and navigated between.\nWhen entering multiple periods in the time filter each proceeding `date_from` must be 1 day after the `date_to` \nthat came before it to maintain sequence order.\n",
                            "required": True,
                        },
                    ),
                    89: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    90: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_colours,
                            "help_text": "\nFilter colour selections are used to represent the colours of a filter across filter linked\ncomponents Eg. a colour chosen for a given geography type such as `UKHSA Region` will be used\nto highlight that region on filter linked charts\n",
                        },
                    ),
                    91: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_geography_type_names,
                            "help_text": "\nThis generates a list of selectable geographies on the dashboard based on the geography type selected\nhere. Eg. A selection of `Lower Tier Local Authority` here will result in all LTLA's being displayed\nin the filter drop down on the dashboard for a user to select from.\n",
                        },
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("colour", 90), ("geography_type", 91)]],
                        {},
                    ),
                    93: (
                        "wagtail.blocks.StreamBlock",
                        [[("geography_filter", 92)]],
                        {
                            "help_text": "\nThis geography filter can be used to setup selectable geography lists based on geography types\nsuch as `UKHSA Region` or `Lower Tier Local Authority`.\n",
                            "min_num": 1,
                        },
                    ),
                    94: ("wagtail.blocks.StructBlock", [[("geography_types", 93)]], {}),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_colours,
                            "help_text": "\nThis colour option is used to represent the threshold across other filter linked components.\nEg: The colour used for the legend on filter linked map component.\n",
                        },
                    ),
                    96: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {
                            "help_text": "\nThe minimum and maximum boundary values are used to set the range for the threshold as a float between\n0.00 and 100 Eg. a threshold of over 95% will have a minimum value of 95 and a maximum value of 100\n",
                            "required": True,
                        },
                    ),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 83),
                                ("colour", 95),
                                ("boundary_minimum_value", 96),
                                ("boundary_maximum_value", 96),
                            ]
                        ],
                        {},
                    ),
                    98: (
                        "wagtail.blocks.StreamBlock",
                        [[("threshold", 97)]],
                        {
                            "help_text": "\nThe threshold filter is used to configure threshold boundaries that can be used to filter data on the dashboard.\nEg. over 95% boundary 95 -> 100\n",
                            "min_num": 1,
                        },
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 83), ("thresholds", 98)]],
                        {},
                    ),
                    100: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "", "required": True},
                    ),
                    101: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_colours,
                            "help_text": "",
                        },
                    ),
                    102: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_theme_names
                        },
                    ),
                    103: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("value", 102)]],
                        {
                            "help_text": "\nThe related theme for the metric. Eg: infectious disease\n"
                        },
                    ),
                    104: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_unique_sub_theme_names
                        },
                    ),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("value", 104)]],
                        {
                            "help_text": "\nThe related sub theme for the metric. Eg: respiratory\n"
                        },
                    ),
                    106: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_topic_names
                        },
                    ),
                    107: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("value", 106)]],
                        {
                            "help_text": "The name of the topic to pull data e.g. COVID-19."
                        },
                    ),
                    108: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_stratum_names
                        },
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("value", 108)]],
                        {
                            "help_text": "\nThe smallest subgroup a piece of data can be broken down into.\nFor example, this could be broken down by ethnicity or testing pillar.\n"
                        },
                    ),
                    110: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_unique_metric_names
                        },
                    ),
                    111: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("value", 110)]],
                        {
                            "help_text": '\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n'
                        },
                    ),
                    112: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_age_names
                        },
                    ),
                    113: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("value", 112)]],
                        {
                            "help_text": "\nThe age band to filter for, if any.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n"
                        },
                    ),
                    114: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_sex_names
                        },
                    ),
                    115: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("value", 114)]],
                        {
                            "help_text": "\nThe gender to filter for, if any.\nThe only options available are `M`, `F` and `ALL`.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n"
                        },
                    ),
                    116: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("theme", 103),
                                ("sub_theme", 105),
                                ("topic", 107),
                                ("stratum", 109),
                                ("metric", 111),
                                ("age", 113),
                                ("sex", 115),
                            ]
                        ],
                        {},
                    ),
                    117: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_geography_names
                        },
                    ),
                    118: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("value", 117)]],
                        {"help_text": ""},
                    ),
                    119: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.metrics_interface.field_choices_callables.get_all_geography_type_names
                        },
                    ),
                    120: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 89), ("value", 119)]],
                        {"help_text": ""},
                    ),
                    121: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("theme", 103),
                                ("sub_theme", 105),
                                ("topic", 107),
                                ("stratum", 109),
                                ("metric", 111),
                                ("age", 113),
                                ("sex", 115),
                                ("geography", 118),
                                ("geography_type", 120),
                            ]
                        ],
                        {},
                    ),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label_prefix", 83),
                                ("label_suffix", 89),
                                ("parameters", 121),
                            ]
                        ],
                        {
                            "help_text": '\nThese additional points configure alternative requests to compare against or supplement the current data filter. For example,\nselecting a `metric` field here could provide a percentage change metric that complements the main data filter selection.\nThe label prefix appears before the metric value in map tooltips, while the suffix appears after.\nFor a percentage change metric, using prefix `change` and suffix `%` would display as "change <value>%" in tooltips.\n',
                            "required": False,
                        },
                    ),
                    123: (
                        "wagtail.blocks.StreamBlock",
                        [[("accompanying_point", 122)]],
                        {
                            "help_text": '\nThese additional points configure alternative requests to compare against or supplement the current data filter. For example,\nselecting a `metric` field here could provide a percentage change metric that complements the main data filter selection.\nThe label prefix appears before the metric value in map tooltips, while the suffix appears after.\nFor a percentage change metric, using prefix `change` and suffix `%` would display as "change <value>%" in tooltips.\n',
                            "required": False,
                        },
                    ),
                    124: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 100),
                                ("colour", 101),
                                ("parameters", 116),
                                ("accompanying_points", 123),
                            ]
                        ],
                        {},
                    ),
                    125: (
                        "wagtail.blocks.StreamBlock",
                        [[("data_filter", 124)]],
                        {
                            "help_text": "\nThe data filter is used to create filter options based on metrics and combined attributes. Eg:\nmetric and stratum.\n",
                            "min_num": 1,
                        },
                    ),
                    126: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("theme", "theme"),
                                ("sub_theme", "sub_theme"),
                                ("topic", "topic"),
                                ("metric", "metric"),
                                ("sex", "sex"),
                                ("age", "age"),
                                ("stratum", "stratum"),
                            ]
                        },
                    ),
                    127: ("wagtail.blocks.StructBlock", [[("data_category", 126)]], {}),
                    128: (
                        "wagtail.blocks.StreamBlock",
                        [[("category", 127)]],
                        {
                            "help_text": "\nSelect the categories for the dropdown options to be grouped by.\nE.g. To build the following:\n<pre>\n|- stratum one\n    |- topic one\n    |- topic two\n| stratum two\n    |- topic one\n    |- topic two\n</pre>\nThe selections for this should be `stratum` and then `topic`.\n",
                            "max_num": 2,
                            "min_num": 1,
                        },
                    ),
                    129: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 83),
                                ("data_filters", 125),
                                ("categories_to_group_by", 128),
                            ]
                        ],
                        {},
                    ),
                    130: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("geography_filters", 94),
                                ("threshold_filters", 99),
                                ("data_filters", 129),
                            ]
                        ],
                        {},
                    ),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 83), ("filters", 130)]],
                        {},
                    ),
                    132: (
                        "wagtail.blocks.StreamBlock",
                        [[("row", 131)]],
                        {
                            "help_text": "\nA filter row can contain one or more filters for the global filter component.\nThey can be used to group filters around a context Eg: data filter with threshold filter.\n",
                            "min_num": 1,
                            "required": True,
                        },
                    ),
                    133: (
                        "wagtail.blocks.StructBlock",
                        [[("time_range", 88), ("rows", 132)]],
                        {
                            "help_text": "\nThe global filter component enables a user of the dashboard to create a variable number of filters\nwhich can be applied across multi components on a dashboard page. This CMS component can be used to configure \nthose options.\n"
                        },
                    ),
                    134: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nThis will form the prefix of the title which will be associated with the filter linked component.\nThe full title will be structured as follows:\n\n<pre>\n[this prefix] between [the selected time period label] ([the selected region], [the selected lower geography type value]).\n</pre>\n",
                            "required": True,
                        },
                    ),
                    135: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "",
                            "features": ["h2", "h3", "h4", "bold", "ul", "link"],
                            "help_text": "\nAn optional body of text to accompany this block. This text will be displayed in the about content for this map.\n",
                            "required": False,
                        },
                    ),
                    136: (
                        "wagtail.blocks.StructBlock",
                        [[("title_prefix", 134), ("about", 135)]],
                        {
                            "help_text": "\nThis filter linked map can be used to display metric data configured through a data filter\nin the global filter component to represent this data geographically.\n",
                            "required": False,
                        },
                    ),
                    137: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nThis legend title will be used for the title of the sub plot chart legends. \nEg. the colours associated with the geographies from global filter.\n",
                            "required": True,
                        },
                    ),
                    138: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "help_text": "\nAn optional value to draw a target threshold for.\n",
                            "required": False,
                        },
                    ),
                    139: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nAn optional label to add as for the target threshold indicator on the charts.\n",
                            "required": False,
                        },
                    ),
                    140: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "",
                            "features": ["h2", "h3", "h4", "bold", "ul", "link"],
                            "help_text": "\nAn optional body of text to accompany this block. This text will be displayed in the about content of the chart.\n",
                            "required": False,
                        },
                    ),
                    141: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title_prefix", 134),
                                ("legend_title", 137),
                                ("target_threshold", 138),
                                ("target_threshold_label", 139),
                                ("about", 140),
                            ]
                        ],
                        {
                            "help_text": "\nThis filter linked sub plot chart can be used to display metric data configured through a data filter\nin the global filter component. \nThis template will render a new chart for each geography selected by the user \nfor the selected entities according to the data filter.\n",
                            "required": False,
                        },
                    ),
                    142: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nThis legend title will be used for the title of the time series chart legends. \nEg. the colours associated with the selected data entities from global filter.\n",
                            "required": True,
                        },
                    ),
                    143: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title_prefix", 134),
                                ("legend_title", 142),
                                ("about", 140),
                            ]
                        ],
                        {
                            "help_text": "\nThis filter linked time series chart can be used to display metric data configured through a data filter\nin the global filter component. \nThis template will render a new chart for each geography selected by the user \nfor the selected entities according to the data filter.\n",
                            "required": False,
                        },
                    ),
                    144: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text_card", 2),
                                ("chart_row_card", 77),
                                ("headline_numbers_row_card", 82),
                                ("global_filter_card", 133),
                                ("filter_linked_map", 136),
                                ("filter_linked_sub_plot_chart_template", 141),
                                ("filter_linked_time_series_chart_template", 143),
                            ]
                        ],
                        {
                            "help_text": "\nHere you can add any number of content row cards for this section.\nNote that these cards will be displayed across the available width.\n"
                        },
                    ),
                    145: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 144)]],
                        {},
                    ),
                },
            ),
        ),
    ]
