# Generated by Django 5.1.7 on 2025-05-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0024_alter_topicpageannouncement_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topicpageannouncement",
            options={},
        ),
    ]
