# Generated by Django 5.2.11 on 2026-02-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0024_alter_topicpage_add_confidence_interval_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="enable public page"),
            preserve_default=False,
        ),
    ]
