# Generated by Django 5.2.11 on 2026-03-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0027_topicpage_page_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicpage",
            name="page_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("official", "Official"),
                    ("official_sensitive", "Official Sensitive"),
                    ("protective_marking_not_set", "Protective Marking Not Set"),
                    ("secret", "Secret"),
                    ("top_secret", "Top Secret"),
                ],
                default="official_sensitive",
                help_text="\nThe classification level of all data on this page (only applies to non-public pages). Defaults to `Official-Sensitive`.\n",
                max_length=50,
                null=True,
            ),
        ),
    ]
