# Generated by Django 5.2.9 on 2026-03-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0029_alter_topicpage_body_date_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="page_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("official", "Official"),
                    ("official_sensitive", "Official Sensitive"),
                    ("protective_marking_not_set", "Protective Marking Not Set"),
                    ("secret", "Secret"),
                    ("top_secret", "Top Secret"),
                ],
                default=None,
                help_text="\nThe classification level of all data on this page (only applies to non-public pages). Defaults to `Official-Sensitive`.\n",
                max_length=50,
                null=True,
            ),
            preserve_default=False,
        ),
    ]
