# Generated by Django 5.2.9 on 2026-03-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0028_alter_topicpage_page_classification"),
        ("topic", "0029_alter_topicpage_body_date_prefix"),
    ]

    operations = []
