# Generated by Django 5.2.13 on 2026-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0031_alter_topicpage_page_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="sub_theme",
            field=models.CharField(
                blank=True,
                default="",
                help_text="\nThe subtheme must be provided for a non-public page.\n",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="topicpage",
            name="theme",
            field=models.CharField(
                blank=True,
                default="",
                help_text="\nThe theme must be provided for a non-public page.\n",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="topicpage",
            name="topic",
            field=models.CharField(
                blank=True,
                default="",
                help_text="\nThe topic must be provided for a non-public page.\n",
                max_length=255,
                null=True,
            ),
        ),
    ]
