# Generated by Django 5.2.13 on 2026-04-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0032_topicpage_sub_theme_topicpage_theme_topicpage_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicpage",
            name="sub_theme",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="theme",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
