# Generated by Django 5.2.16 on 2026-07-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0036_alter_topicpage_add_HeadlineChartWithDescriptionCard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topicpage",
            old_name="theme",
            new_name="page_theme",
        ),
        migrations.RenameField(
            model_name="topicpage",
            old_name="sub_theme",
            new_name="page_sub_theme",
        ),
        migrations.RenameField(
            model_name="topicpage",
            old_name="topic",
            new_name="page_topic",
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="page_theme",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="page_sub_theme",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="page_topic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="page_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("official", "Official"),
                    ("official_sensitive", "Official Sensitive"),
                    ("protective_marking_not_set", "Protective Marking Not Set"),
                    ("secret", "Secret"),
                    ("top_secret", "Top Secret"),
                ],
                default="",
                help_text="\nThe classification level of all data on this page (only applies to non-public pages). Defaults to `Official-Sensitive`.\n",
                max_length=50,
            ),
        ),
    ]
