# Generated by Django 5.2.17 on 2026-09-20 19:14

from django.db import migrations, models
from django.db.models import F


def forwards(apps, schema_editor):
    """
    Forward data migration.

    Args:
        apps: the apps object to get the models from
        schema_editor: the schema_editor object
    """
    TopicPage = apps.get_model("topic", "TopicPage")
    TopicPage.objects.filter(is_public=True).update(
        page_classification="",
        page_theme="",
        page_sub_theme="",
        page_topic="",
    )
    TopicPage.objects.filter(is_public=False).update(
        page_theme=F("theme"),
        page_sub_theme=F("sub_theme"),
        page_topic=F("topic"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0037_add_dual_cat_chart_date_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="page_sub_theme",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="topicpage",
            name="page_theme",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="topicpage",
            name="page_topic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="page_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("official", "Official"),
                    ("official_sensitive", "Official Sensitive"),
                    ("protective_marking_not_set", "Protective Marking Not Set"),
                    ("secret", "Secret"),
                    ("top_secret", "Top Secret"),
                ],
                default="",
                help_text="\nThe classification level of all data on this page (only applies to non-public pages). Defaults to `Official-Sensitive`.\n",
                max_length=50,
            ),
        ),
        migrations.RunPython(code=forwards, reverse_code=migrations.RunPython.noop),
    ]
