# Generated by Django 5.2.17 on 2026-09-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0038_topicpage_page_sub_theme_topicpage_page_theme_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topicpage",
            name="sub_theme",
        ),
        migrations.RemoveField(
            model_name="topicpage",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="topicpage",
            name="topic",
        ),
    ]
