# Generated by Django 5.2.12 on 2026-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermissionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated display name",
                        max_length=500,
                    ),
                ),
                ("theme", models.CharField(default="", max_length=255)),
                ("sub_theme", models.CharField(default="", max_length=255)),
                ("topic", models.CharField(default="", max_length=255)),
                ("metric", models.CharField(default="", max_length=255)),
                ("geography_type", models.CharField(default="", max_length=255)),
                ("geography", models.CharField(default="", max_length=255)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "theme",
                            "sub_theme",
                            "topic",
                            "metric",
                            "geography_type",
                            "geography",
                        ),
                        name="unique_permission_set",
                    )
                ],
            },
        ),
    ]
