# Generated by Django 5.2.12 on 2026-03-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("infectious_disease", "Infectious Disease"),
                            ("extreme_event", "Extreme Event"),
                            ("non-communicable", "Non Communicable"),
                            ("climate_and_environment", "Climate And Environment"),
                            ("immunisation", "Immunisation"),
                        ]
                    ),
                ),
                (
                    "sub_theme",
                    models.CharField(
                        choices=[
                            ("vaccine_preventable", "Vaccine Preventable"),
                            ("respiratory", "Respiratory"),
                            ("bloodstream_infection", "Bloodstream Infection"),
                            ("bloodborne", "Bloodborne"),
                            ("gastrointestinal", "Gastrointestinal"),
                            ("antimicrobial_resistance", "Antimicrobial Resistance"),
                            ("contact", "Contact"),
                            ("childhood_illness", "Childhood Illness"),
                            (
                                "invasive_bacterial_infections",
                                "Invasive Bacterial Infections",
                            ),
                            ("vector_borne", "Vector Borne"),
                        ]
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("metric", models.CharField(max_length=255)),
                ("geography_type", models.CharField(max_length=255)),
                ("geography", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="AuthFeature",
        ),
    ]
