# Generated by Django 5.2.12 on 2026-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionSets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=255)),
                ("sub_theme", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("metric", models.CharField(max_length=255)),
                ("geography_type", models.CharField(max_length=255)),
                ("geography", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="AuthFeature",
        ),
    ]
