# Generated by Django 5.2.12 on 2026-03-30 08:54

import django.core.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_entra_id",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$"
                            )
                        ]
                    ),
                ),
                (
                    "permission_set",
                    wagtail.fields.StreamField(
                        [("section", 0)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("", "...............")]},
                            )
                        },
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="geography_type",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="theme",
            field=models.CharField(default="", max_length=255),
        ),
    ]
