# Generated by Django 5.2.12 on 2026-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="geography_type",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="theme",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(unique=True)),
                (
                    "permission_sets",
                    models.ManyToManyField(blank=True, to="auth_content.permissionset"),
                ),
            ],
        ),
    ]
