# Generated by Django 5.2.12 on 2026-03-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0002_permissionsets_delete_authfeature"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PermissionSets",
            new_name="PermissionSet",
        ),
    ]
