# Generated by Django 5.2.9 on 2026-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0002_permissionset_delete_authfeature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="geography",
            field=models.CharField(blank=True, default="*", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="geography_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("*", "* (All)"),
                    ("United Kingdom", "United Kingdom"),
                    ("Nation", "Nation"),
                    ("Lower Tier Local Authority", "Lower Tier Local Authority"),
                    ("NHS Region", "NHS Region"),
                    ("NHS Trust", "NHS Trust"),
                    ("Upper Tier Local Authority", "Upper Tier Local Authority"),
                    ("UKHSA Region", "UKHSA Region"),
                    ("UKHSA Super-Region", "UKHSA Super-Region"),
                    ("Government Office Region", "Government Office Region"),
                    ("Integrated Care Board", "Integrated Care Board"),
                    ("Sub-Integrated Care Board", "Sub-Integrated Care Board"),
                    ("Region", "Region"),
                ],
                default="*",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="metric",
            field=models.IntegerField(
                default=-1, help_text="Select a specific metric or * for all metrics"
            ),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="sub_theme",
            field=models.IntegerField(
                default=-1,
                help_text="Select a specific sub-theme or * for all sub-themes",
            ),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="theme",
            field=models.IntegerField(
                default=-1, help_text="Select a specific theme or * for all themes"
            ),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="topic",
            field=models.IntegerField(
                default=-1, help_text="Select a specific topic or * for all topics"
            ),
        ),
    ]
