# Generated by Django 5.2.12 on 2026-03-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0004_alter_permissionset_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="theme",
            field=models.CharField(
                choices=[
                    ("infectious_disease", "Infectious Disease"),
                    ("extreme_event", "Extreme Event"),
                    ("non-communicable", "Non Communicable"),
                    ("climate_and_environment", "Climate And Environment"),
                    ("immunisation", "Immunisation"),
                ]
            ),
        ),
    ]
