# Generated by Django 5.2.9 on 2026-03-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0006_alter_permissionset_geography_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="geography",
            field=models.CharField(blank=True, default="-1", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="metric",
            field=models.CharField(blank=True, default="-1", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="sub_theme",
            field=models.CharField(blank=True, default="-1", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-1", "* (All themes)"),
                    ("3", "extreme_event"),
                    ("1", "immunisation"),
                    ("2", "infectious_disease"),
                    ("4", "non-communicable"),
                ],
                default="-1",
                max_length=255,
            ),
        ),
    ]
