# Generated by Django 5.2.9 on 2026-03-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0007_alter_permissionset_geography_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="topic",
            field=models.CharField(blank=True, default="-1", max_length=255),
        ),
    ]
