# Generated by Django 5.2.12 on 2026-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0008_alter_permissionset_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="geography",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="geography_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("United Kingdom", "United Kingdom"),
                    ("Nation", "Nation"),
                    ("Lower Tier Local Authority", "Lower Tier Local Authority"),
                    ("NHS Region", "NHS Region"),
                    ("NHS Trust", "NHS Trust"),
                    ("Upper Tier Local Authority", "Upper Tier Local Authority"),
                    ("UKHSA Region", "UKHSA Region"),
                    ("UKHSA Super-Region", "UKHSA Super-Region"),
                    ("Government Office Region", "Government Office Region"),
                    ("Integrated Care Board", "Integrated Care Board"),
                    ("Sub-Integrated Care Board", "Sub-Integrated Care Board"),
                    ("Region", "Region"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="metric",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="sub_theme",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("-1", "* (All themes)"),
                    ("3", "extreme_event"),
                    ("1", "immunisation"),
                    ("2", "infectious_disease"),
                    ("4", "non-communicable"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
