# Generated by Django 5.2.9 on 2026-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0009_alter_permissionset_geography_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="geography_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("-1", "* (All geography-types)"),
                    ("1", "Region"),
                    ("2", "Upper Tier Local Authority"),
                    ("3", "Nation"),
                    ("4", "Lower Tier Local Authority"),
                    ("5", "Government Office Region"),
                    ("6", "United Kingdom"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="permissionset",
            constraint=models.UniqueConstraint(
                fields=(
                    "theme",
                    "sub_theme",
                    "topic",
                    "metric",
                    "geography_type",
                    "geography",
                ),
                name="unique_permission_set",
            ),
        ),
    ]
