# Generated by Django 5.2.9 on 2026-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0010_alter_permissionset_geography_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionset",
            name="name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated display name",
                max_length=500,
            ),
        ),
    ]
