# Generated by Django 5.2.9 on 2026-03-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0011_permissionset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="geography",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="geography_type",
            field=models.CharField(
                choices=[
                    ("", "---------"),
                    ("-1", "* (All geography-types)"),
                    ("1", "Region"),
                    ("2", "Upper Tier Local Authority"),
                    ("3", "Nation"),
                    ("4", "Lower Tier Local Authority"),
                    ("5", "Government Office Region"),
                    ("6", "United Kingdom"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="metric",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="sub_theme",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="theme",
            field=models.CharField(
                choices=[
                    ("", "---------"),
                    ("-1", "* (All themes)"),
                    ("3", "extreme_event"),
                    ("1", "immunisation"),
                    ("2", "infectious_disease"),
                    ("4", "non-communicable"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="topic",
            field=models.CharField(default="", max_length=255),
        ),
    ]
