# Generated by Django 5.2.13 on 2026-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0002_alter_permissionset_geography_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionset",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="\nThis is an (optional) user readable name for the permission set. If not set, a default autogenerated name will be used.\n",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="permissionset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("display_name__isnull", False)),
                fields=("display_name",),
                name="unique_non_null_display_name",
            ),
        ),
    ]
