# Generated by Django 5.2.13 on 2026-05-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0002_alter_permissionset_geography_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionset",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="\nThis is an (optional) user readable name for the permission set. If not set, a default autogenerated name will be used.\n",
                max_length=255,
                unique=True,
            ),
        ),
    ]
