# Generated by Django 5.2.15 on 2026-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0003_permissionset_display_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_id", models.UUIDField(unique=True)),
                (
                    "application_name",
                    models.CharField(
                        blank=True, help_text="Application display name", max_length=500
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this application still active?"
                    ),
                ),
                (
                    "permission_sets",
                    models.ManyToManyField(blank=True, to="auth_content.permissionset"),
                ),
            ],
        ),
    ]
