# Generated by Django 5.0.2 on 2024-02-19 14:34

import cms.dynamic_content.blocks
import cms.dynamic_content.sections
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.blocks.RichTextBlock(
                            help_text="\nA required body of text to accompany this block.\n",
                            required=True,
                        ),
                    ),
                    (
                        "button",
                        cms.dynamic_content.blocks.ButtonChooserBlock(
                            "snippets.button", required=False
                        ),
                    ),
                    (
                        "code_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        help_text="\nThe text you add here will be used as the heading for this section. \n",
                                        required=True,
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "code_snippet",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "language",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=cms.dynamic_content.sections.get_languages
                                                            ),
                                                        ),
                                                        (
                                                            "code",
                                                            wagtail.blocks.TextBlock(
                                                                form_classname="codeblock_monospace"
                                                            ),
                                                        ),
                                                    ],
                                                    help_text="\nA code snippet that allows a choice of language \n",
                                                ),
                                            )
                                        ],
                                        help_text='\nAn optional section that can be used to include codeblocks to the content, this includes\na heading to describe the code example to following and the ability to add multiple "code snippets"\nto show the example in multiple languages.\n',
                                        required=True,
                                    ),
                                ),
                            ],
                            help_texts="placeholder code block single example multiple languages possible",
                        ),
                    ),
                ]
            ),
        ),
    ]
