# Generated by Django 5.0.2 on 2024-03-07 15:50

import cms.dynamic_content.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composite", "0003_alter_compositepage_body_include_external_button_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "text",
                        wagtail.blocks.RichTextBlock(
                            features=["h2", "h3", "h4", "bold", "ul", "link", "code"],
                            help_text="\nA required body of text to accompany this block.\n",
                            required=True,
                        ),
                    ),
                    (
                        "code_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        help_text="\nThe text you add here will be used as the heading for this section. \n",
                                        required=False,
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "code_snippet",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "language",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=cms.dynamic_content.blocks.ProgrammingLanguages.get_programming_languages
                                                            ),
                                                        ),
                                                        (
                                                            "code",
                                                            wagtail.blocks.TextBlock(
                                                                form_classname="codeblock_monospace",
                                                                help_text="\nA code snippet to demonstrate the example. Please note that HTML type content is not permitted.\n",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        help_text="\nA required section that can be used to add code examples to a composite page type.\n",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "button",
                        cms.dynamic_content.blocks.ButtonChooserBlock(
                            "snippets.button", required=False
                        ),
                    ),
                    (
                        "external_button",
                        cms.dynamic_content.blocks.ExternalButtonChooserBlock(
                            "snippets.externalbutton", required=False
                        ),
                    ),
                ]
            ),
        ),
    ]
