# Generated by Django 5.1 on 2024-08-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composite", "0009_add_seo_change_frequency_and_priority_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositepage",
            name="related_links_layout",
            field=models.CharField(
                choices=[("Sidebar", "Sidebar"), ("Footer", "Footer")],
                default="Sidebar",
                help_text="\nThis dictates where the related links for this page will be positioned.\n",
                max_length=10,
                verbose_name="Layout",
            ),
        ),
    ]
