# Generated by Django 5.1.2 on 2024-11-05 13:36

import cms.dynamic_content.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composite", "0011_add_pagination_control_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("code_block", 6),
                    ("internal_button", 7),
                    ("external_button", 8),
                    ("wha_button", 9),
                    ("internal_page_links", 14),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "ul",
                                "link",
                                "code",
                            ],
                            "help_text": "\nA required body of text to accompany this block.\n",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nThe text you add here will be used as the heading for this section. \n",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": cms.dynamic_content.blocks.ProgrammingLanguages.get_programming_languages
                        },
                    ),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "form_classname": "codeblock_monospace",
                            "help_text": "\nA code snippet to demonstrate the example. Please note that HTML type content is not permitted.\n",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 2), ("code", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StreamBlock",
                        [[("code_snippet", 4)]],
                        {
                            "help_text": "\nA required section that can be used to add code examples to a composite page type.\n",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("content", 5)]],
                        {},
                    ),
                    7: (
                        "cms.dynamic_content.blocks.InternalButtonChooserBlock",
                        ("snippets.internalbutton",),
                        {"required": False},
                    ),
                    8: (
                        "cms.dynamic_content.blocks.ExternalButtonChooserBlock",
                        ("snippets.externalbutton",),
                        {"required": False},
                    ),
                    9: (
                        "cms.dynamic_content.blocks.WhaButtonChooserBlock",
                        ("snippets.weatheralertbutton",),
                        {"required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nThis is the title of the page you're linking to Eg. COVID-19\n",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "\nThis is an optional short description of the page you're linking to.\n",
                            "required": False,
                        },
                    ),
                    12: (
                        "cms.dynamic_content.blocks.PageLinkChooserBlock",
                        (),
                        {"page_type": ["topic.TopicPage"]},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 10), ("sub_title", 11), ("page", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.StreamBlock", [[("page_link", 13)]], {}),
                },
            ),
        ),
    ]
