# Generated by Django 5.1.2 on 2024-11-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composite", "0012_alter_compositepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compositepage",
            name="date_posted",
        ),
    ]
