# Generated by Django 5.1.7 on 2025-04-01 12:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composite", "0014_compositepageannouncement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositepageannouncement",
            name="banner_type",
            field=models.CharField(
                choices=[("Information", "Information"), ("Warning", "Warning")],
                default="Information",
                help_text="\nThe type to associate with the announcement. Defaults to `Information`.\n",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="compositepageannouncement",
            name="body",
            field=wagtail.fields.RichTextField(
                help_text="\nA body of text to be displayed by the announcement. There is a limit of 255 characters for this field.\n",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="compositepageannouncement",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="\nWhether to activate this banner only on this individual page. \nNote that multiple page banners can be active on one page. Consider \ncarefully if you need multiple announcements to be active at once as\nthis can have an impact on user experience of the dashboard page.\n",
            ),
        ),
        migrations.AlterField(
            model_name="compositepageannouncement",
            name="title",
            field=models.CharField(
                help_text="\nThe title to associate with the announcement. This must be provided.\n",
                max_length=255,
            ),
        ),
    ]
