# Generated by Django 5.1.7 on 2025-04-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composite", "0015_alter_compositepageannouncement_banner_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compositepageannouncement",
            options={},
        ),
    ]
