# Generated by Django 5.1.7 on 2025-04-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composite", "0016_alter_compositepageannouncement_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compositepageannouncement",
            name="badge",
        ),
    ]
