# Generated by Django 5.1.7 on 2025-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composite", "0017_remove_compositepageannouncement_badge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compositepageannouncement",
            options={"base_manager_name": "objects"},
        ),
    ]
