name: 'Setup virtual environment'

description: 'Setup virtual environment & install dependencies'

runs:
  using: "composite"
  steps:
    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
      shell: bash

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
      shell: bash

    - name: Install dependencies
      run: |
        pip install -r requirements.txt --no-cache-dir
      shell: bash
