# Generated by Django 5.2.9 on 2026-02-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acknowledgement", "0002_acknowledgementpage_seo_change_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acknowledgementpage",
            name="terms_of_service_link_text",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="acknowledgementpage",
            name="agree_button",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="acknowledgementpage",
            name="disagree_button",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="acknowledgementpage",
            name="i_agree_checkbox",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="acknowledgementpage",
            name="terms_of_service_link",
            field=models.URLField(
                max_length=400, verbose_name="Terms of Service (URL)"
            ),
        ),
    ]
