# Generated by Django 5.2.9 on 2026-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "acknowledgement",
            "0003_acknowledgementpage_terms_of_service_link_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="acknowledgementpage",
            name="terms_of_service_error",
            field=models.CharField(default="Accept terms", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="acknowledgementpage",
            name="terms_of_service_link",
            field=models.URLField(max_length=400, verbose_name="Terms of service link"),
        ),
    ]
