# Generated by Django 5.2.9 on 2026-03-04 11:50

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acknowledgement", "0004_acknowledgementpage_terms_of_service_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acknowledgementpage",
            name="body",
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="acknowledgementpage",
            name="i_agree_checkbox",
            field=models.CharField(
                max_length=255, verbose_name="I agree checkbox label"
            ),
        ),
        migrations.AlterField(
            model_name="acknowledgementpage",
            name="terms_of_service_link",
            field=models.URLField(max_length=400),
        ),
    ]
