VALID_PARAMETERS = [
    (
        "infectious_disease",
        "respiratory",
        "COVID-19",
        "COVID-19_deaths_ONSByWeek",
        "deaths",
    ),
    (
        "climate_and_environment",
        "vectors",
        "ticks",
        "ticks_counts_countByYear",
        "counts",
    ),
    (
        "infectious_disease",
        "invasive_bacterial_infections",
        "iGAS",
        "iGAS_cases_rateByMonth",
        "cases",
    ),
]
