# Generated by Django 5.2.9 on 2026-03-12 15:30

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_change_frequency",
                    models.IntegerField(
                        choices=[
                            (1, "Always"),
                            (2, "Hourly"),
                            (3, "Daily"),
                            (4, "Weekly"),
                            (5, "Monthly"),
                            (6, "Yearly"),
                            (7, "Never"),
                        ],
                        default=5,
                        help_text="<p>This value tells search engines how often a page’s content updates, offering a hint for crawling prioritization.</p>\n<p><strong>Always</strong>: This means the page is constantly changing with important, up-to-the-minute updates. \nA subreddit index page, a stock market data page, and the index page of a major news site might use this tag.</p>\n<p><strong>Hourly</strong>: The page is updated on an hourly basis or thereabouts.\n Major news sites, weather sites, and active web forums might use this tag.</p>\n<p><strong>Daily</strong>: The page is updated with new content on average once a day. \nSmall web forums, classified ad pages, daily newspapers, and daily blogs might use this tag for their homepage.</p>\n<p><strong>Weekly</strong>: The page is updated around once a week with new content. \nProduct info pages with daily pricing information, small blogs, and website directories use this tag.</p>\n<p><strong>Monthly</strong>: The page is updated around once a month; maybe more, maybe less. \nCategory pages, evergreen guides with updated information, and FAQs often use this tag.</p>\n<p><strong>Yearly</strong>: The page is rarely updated but may receive updates once or twice a year. \nMany static pages, such as registration pages, About pages, and privacy policies, fall into this category.</p>\n<p><strong>Never</strong>: The page is never going to be updated. \nOld blog entries, old news stories, and completely static pages fall into this category. </p>",
                        verbose_name="SEO change frequency",
                    ),
                ),
                (
                    "seo_priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.5,
                        help_text="\nThis value signals the importance of a page to search engines. \nAssigning accurate priority values to key pages of your site can help search engines understand \nthe structure and hierarchy of your content.\nThis must be a number between 0.1 - 1.0.\n",
                        max_digits=2,
                        validators=[
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                            django.core.validators.MinValueValidator(Decimal("0.1")),
                        ],
                        verbose_name="SEO priority",
                    ),
                ),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "error_line",
                    models.TextField(
                        blank=True,
                        help_text="\nThis is the error summary text that will be displayed in red at the top of the error view.\n",
                        null=True,
                    ),
                ),
                (
                    "error_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="\nThis is a rich text field that can be used to display detailed information about the error that the user is experiencing\n",
                        null=True,
                    ),
                ),
                (
                    "sub_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="\nThis is a rich text field that can be used to display further information to the user. This text will appear below the error at the top of the page.\n",
                        null=True,
                    ),
                ),
                (
                    "related_links_layout",
                    models.CharField(
                        choices=[("Sidebar", "Sidebar"), ("Footer", "Footer")],
                        default="Footer",
                        help_text="\nThis dictates where the related links for this page will be positioned.\n",
                        max_length=10,
                        verbose_name="Layout",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ErrorPageAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="\nThe title to associate with the announcement. This must be provided.\n",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        help_text="\nA body of text to be displayed by the announcement. There is a limit of 255 characters for this field.\n",
                        max_length=255,
                    ),
                ),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("Information", "Information"),
                            ("Warning", "Warning"),
                        ],
                        default="Information",
                        help_text="\nThe type to associate with the announcement. Defaults to `Information`.\n",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="\nWhether to activate this banner only on this individual page. \nNote that multiple page banners can be active on one page. Consider \ncarefully if you need multiple announcements to be active at once as\nthis can have an impact on user experience of the dashboard page.\n",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to="error.errorpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ErrorPageRelatedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=400, verbose_name="URL")),
                ("body", wagtail.fields.RichTextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_links",
                        to="error.errorpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
