# Generated by Django 5.2.12 on 2026-03-12 10:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("error", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorpage",
            name="error_line",
            field=models.TextField(
                blank=True,
                help_text="\nThis is the error summary text that will be displayed in red at the top of the error view.\n",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="errorpage",
            name="error_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="\nThis is the rich text field that can be used to display detailed information about the error that the user is experiencing",
                null=True,
            ),
        ),
    ]
