# Generated by Django 5.2.9 on 2026-03-12 11:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("error", "0002_errorpage_error_line_errorpage_error_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorpage",
            name="sub_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="\nThis is a rich text field that can be used to display further information to the user. This text will appear below the error at the top of the page.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="errorpage",
            name="error_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="\nThis is a rich text field that can be used to display detailed information about the error that the user is experiencing\n",
                null=True,
            ),
        ),
    ]
