# Generated by Django 5.2.9 on 2026-03-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("error", "0003_errorpage_sub_text_alter_errorpage_error_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorpage",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
