# Generated by Django 4.1.7 on 2023-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_core_and_flat_data_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geography",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="geographytype",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="stratum",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="subtheme",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="theme",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weeklytimeseries",
            name="geography",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weeklytimeseries",
            name="geography_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weeklytimeseries",
            name="metric",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weeklytimeseries",
            name="metric_value",
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weeklytimeseries",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="weeklytimeseries",
            name="stratum",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weeklytimeseries",
            name="sub_theme",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weeklytimeseries",
            name="theme",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weeklytimeseries",
            name="topic",
            field=models.CharField(max_length=50),
        ),
    ]
