# Generated by Django 4.1.9 on 2023-06-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_add_age_table_update_with_time_period_enum"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreHeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        help_text="\nSex of patients.\n", max_length=3, null=True
                    ),
                ),
                (
                    "refresh_date",
                    models.DateField(
                        help_text="\nThe date which this piece of data was last updated.\n"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="\nStart of the period for which this figure is being provided.\n"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="\nEnd of the period for which this figure is being provided.\n"
                    ),
                ),
                ("metric_value", models.DecimalField(decimal_places=1, max_digits=11)),
                (
                    "age",
                    models.ForeignKey(
                        help_text="\nAge band of patients.\n",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.age",
                    ),
                ),
                (
                    "geography",
                    models.ForeignKey(
                        help_text="\nThe name of the geography associated with the metric e.g. `London`\n",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.geography",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        help_text="\nThe name of the metric e.g. `COVID-19_headline_ONSdeaths_7daychange`\n",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.metric",
                    ),
                ),
                (
                    "stratum",
                    models.ForeignKey(
                        help_text="\nSmallest subgroup a metric can be broken down into (e.g. ethnicity, testing pillar) excluding age and sex.\nIf a metric cannot be further broken down into strata, the value for stratum will be 'default'\n",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.stratum",
                    ),
                ),
            ],
        ),
    ]
