# Generated by Django 4.1.9 on 2023-06-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_add_coreheadline_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coretimeseries",
            old_name="period",
            new_name="metric_frequency",
        ),
        migrations.AddField(
            model_name="coretimeseries",
            name="age",
            field=models.ForeignKey(
                help_text="\nAge band of patients.\n",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data.age",
            ),
        ),
        migrations.AddField(
            model_name="coretimeseries",
            name="month",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="coretimeseries",
            name="refresh_date",
            field=models.DateField(
                help_text="\nThe date which this piece of data was last updated.\n",
                null=True,
            ),
        ),
    ]
