# Generated by Django 4.1.9 on 2023-07-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_rename_period_to_metric_frequency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.topic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="metric",
            name="metric_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data.metricgroup",
            ),
        ),
    ]
