# Generated by Django 4.2.3 on 2023-08-01 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0011_rename_dt_coretimeseries_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apitimeseries",
            old_name="dt",
            new_name="date",
        ),
    ]
