# Generated by Django 4.2.3 on 2023-08-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0013_rename_period_apitimeseries_metric_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitimeseries",
            name="geography",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="apitimeseries",
            name="metric",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="geography",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
