# Generated by Django 4.2.3 on 2023-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0014_bump_max_char_limit_for_metric_name_and_geography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coretimeseries",
            name="metric_value",
            field=models.DecimalField(decimal_places=4, max_digits=11),
        ),
    ]
