# Generated by Django 4.2.4 on 2023-10-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0015_increase_coretimeseries_metric_value_to_4dp"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="age",
            constraint=models.UniqueConstraint(
                fields=("name",), name="`Age` name should be unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="geography",
            constraint=models.UniqueConstraint(
                fields=("name", "geography_type"),
                name="`Geography` and `GeographyType` should be a unique combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="geographytype",
            constraint=models.UniqueConstraint(
                fields=("name",), name="`GeographyType` name should be unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.UniqueConstraint(
                fields=("name",), name="`Metric` name should be unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.UniqueConstraint(
                fields=("name", "topic"),
                name="`Metric` and `Topic` should be a unique combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricgroup",
            constraint=models.UniqueConstraint(
                fields=("name", "topic"),
                name="`MetricGroup` and `Topic` should be a unique combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="stratum",
            constraint=models.UniqueConstraint(
                fields=("name",), name="`Stratum` name should be unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtheme",
            constraint=models.UniqueConstraint(
                fields=("name",), name="`SubTheme` name should be unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtheme",
            constraint=models.UniqueConstraint(
                fields=("name", "theme"),
                name="`SubTheme` and `Theme` should be a unique combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("name",), name="`Theme` name should be unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("name",), name="`Topic` name should be unique"
            ),
        ),
    ]
