# Generated by Django 4.2.6 on 2023-10-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0016_add_unique_constraints_against_supporting_core_models"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coretimeseries",
            constraint=models.UniqueConstraint(
                fields=(
                    "metric",
                    "geography",
                    "stratum",
                    "age",
                    "sex",
                    "year",
                    "month",
                    "epiweek",
                    "date",
                    "metric_value",
                ),
                name="The `CoreTimeSeries` record should be unique",
            ),
        ),
    ]
