# Generated by Django 4.2.6 on 2023-10-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0017_coretimeseries_record_should_be_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coreheadline",
            constraint=models.UniqueConstraint(
                fields=(
                    "metric",
                    "geography",
                    "stratum",
                    "age",
                    "sex",
                    "period_start",
                    "period_end",
                    "metric_value",
                ),
                name="The `CoreHeadline` record should be unique",
            ),
        ),
    ]
