# Generated by Django 4.2.6 on 2023-10-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0018_coreheadline_record_should_be_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="apitimeseries",
            constraint=models.UniqueConstraint(
                fields=(
                    "metric",
                    "topic",
                    "theme",
                    "sub_theme",
                    "geography",
                    "geography_type",
                    "geography_code",
                    "stratum",
                    "age",
                    "sex",
                    "year",
                    "month",
                    "epiweek",
                    "date",
                    "metric_value",
                ),
                name="The `APITimeSeries` record should be unique",
            ),
        ),
    ]
