# Generated by Django 4.2.7 on 2024-02-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0021_add_related_name_of_geographies_out_to_geography_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitimeseries",
            name="refresh_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="coreheadline",
            name="refresh_date",
            field=models.DateTimeField(
                help_text="\nThe date which this piece of data was last updated.\n"
            ),
        ),
        migrations.AlterField(
            model_name="coretimeseries",
            name="refresh_date",
            field=models.DateTimeField(
                help_text="\nThe date which this piece of data was last updated.\n",
                null=True,
            ),
        ),
    ]
