# Generated by Django 5.0.6 on 2024-07-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0023_set_period_start_and_end_fields_to_datetime_on_core_headline"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coretimeseries",
            name="The `CoreTimeSeries` record should be unique",
        ),
        migrations.AddField(
            model_name="coretimeseries",
            name="in_reporting_lag_period",
            field=models.BooleanField(
                blank=True,
                help_text="\nWhether the record falls within the current reporting lag period. \nIf true, then the value is subject to change in a subsequent retrospective update. \nIf false, then the value is considered to be final and static.\nIf null, then the reporting lag has not been considered. \n",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="coretimeseries",
            constraint=models.UniqueConstraint(
                fields=(
                    "metric",
                    "geography",
                    "stratum",
                    "age",
                    "sex",
                    "year",
                    "month",
                    "epiweek",
                    "date",
                    "metric_value",
                    "in_reporting_lag_period",
                ),
                name="The `CoreTimeSeries` record should be unique",
            ),
        ),
    ]
