# Generated by Django 5.0.6 on 2024-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0023_set_period_start_and_end_fields_to_datetime_on_core_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="coretimeseries",
            name="reporting_lag_period",
            field=models.BooleanField(
                blank=True,
                help_text="\nWhether the record falls within the current reporting lag period. \nIf true, then the value is subject to change in a subsequent retrospective update. \nIf false, then the value is considered to be final and static.\nIf null, then the reporting lag has not been considered. \n",
                null=True,
            ),
        ),
    ]
