# Generated by Django 5.0.6 on 2024-07-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_add_reporting_lag_period_field_to_core_time_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitimeseries",
            name="reporting_lag_period",
            field=models.BooleanField(
                blank=True,
                help_text="\nWhether the record falls within the current reporting lag period. \nIf true, then the value is subject to change in a subsequent retrospective update. \nIf false, then the value is considered to be final and static.\n",
                null=True,
            ),
        ),
    ]
