# Generated by Django 5.0.6 on 2024-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_add_in_reporting_lag_period_field_to_core_time_series"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apitimeseries",
            name="The `APITimeSeries` record should be unique",
        ),
        migrations.AddField(
            model_name="apitimeseries",
            name="in_reporting_lag_period",
            field=models.BooleanField(
                default=False,
                help_text="\nWhether the record falls within the current reporting lag period. \nIf true, then the value is subject to change in a subsequent retrospective update.\n",
            ),
        ),
        migrations.AddConstraint(
            model_name="apitimeseries",
            constraint=models.UniqueConstraint(
                fields=(
                    "metric",
                    "topic",
                    "theme",
                    "sub_theme",
                    "geography",
                    "geography_type",
                    "geography_code",
                    "stratum",
                    "age",
                    "sex",
                    "year",
                    "month",
                    "epiweek",
                    "date",
                    "metric_value",
                    "in_reporting_lag_period",
                ),
                name="The `APITimeSeries` record should be unique",
            ),
        ),
    ]
