# Generated by Django 5.0.7 on 2024-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0026_rename_in_reporting_lag_period_to_in_reporting_delay_period"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apitimeseries",
            name="The `APITimeSeries` record should be unique",
        ),
        migrations.RemoveConstraint(
            model_name="coretimeseries",
            name="The `CoreTimeSeries` record should be unique",
        ),
        migrations.AddField(
            model_name="apitimeseries",
            name="force_write",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coretimeseries",
            name="force_write",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="apitimeseries",
            constraint=models.UniqueConstraint(
                condition=models.Q(("force_write", False)),
                fields=(
                    "metric",
                    "topic",
                    "theme",
                    "sub_theme",
                    "geography",
                    "geography_type",
                    "geography_code",
                    "stratum",
                    "age",
                    "sex",
                    "year",
                    "month",
                    "epiweek",
                    "date",
                    "metric_value",
                    "in_reporting_delay_period",
                ),
                name="The `APITimeSeries` record should be unique if `force_write` is False",
            ),
        ),
        migrations.AddConstraint(
            model_name="coretimeseries",
            constraint=models.UniqueConstraint(
                condition=models.Q(("force_write", False)),
                fields=(
                    "metric",
                    "geography",
                    "stratum",
                    "age",
                    "sex",
                    "year",
                    "month",
                    "epiweek",
                    "date",
                    "metric_value",
                    "in_reporting_delay_period",
                ),
                name="The `CoreTimeSeries` record should be unique if `force_write` is False",
            ),
        ),
    ]
