# Generated by Django 5.1 on 2024-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0030_migration_for_st_helens_core_headlines"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apitimeseries",
            index=models.Index(
                fields=[
                    "theme",
                    "sub_theme",
                    "topic",
                    "geography_type",
                    "geography",
                    "metric",
                ],
                name="data_apitim_theme_f71822_idx",
            ),
        ),
    ]
