# Generated by Django 5.1 on 2024-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0030_migration_for_st_helens_core_headlines"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apitimeseries",
            index=models.Index(fields=["theme"], name="data_apitim_theme_0e8b3b_idx"),
        ),
        migrations.AddIndex(
            model_name="apitimeseries",
            index=models.Index(
                fields=["theme", "sub_theme"], name="data_apitim_theme_4ac4c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apitimeseries",
            index=models.Index(
                fields=["theme", "sub_theme", "topic"],
                name="data_apitim_theme_384495_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apitimeseries",
            index=models.Index(
                fields=["theme", "sub_theme", "topic", "geography_type"],
                name="data_apitim_theme_cf6ce3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apitimeseries",
            index=models.Index(
                fields=["theme", "sub_theme", "topic", "geography_type", "geography"],
                name="data_apitim_theme_6b286e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apitimeseries",
            index=models.Index(
                fields=[
                    "theme",
                    "sub_theme",
                    "topic",
                    "geography_type",
                    "geography",
                    "metric",
                ],
                name="data_apitim_theme_f71822_idx",
            ),
        ),
    ]
