# Generated by Django 5.1.1 on 2024-10-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0032_data_migration_for_updated_geography_codes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="rounding",
        ),
    ]
