# Generated by Django 5.1.5 on 2025-01-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0033_remove_rounding_column_from_metric_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subtheme",
            name="`SubTheme` name should be unique",
        ),
    ]
