# Generated by Django 5.1.5 on 2025-02-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0034_remove_subtheme_name_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreheadline",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coretimeseries",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
    ]
