# Generated by Django 5.1.6 on 2025-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0035_set_topic_and_subtheme_join_to_be_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitimeseries",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coreheadline",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="coretimeseries",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
