# Generated by Django 5.1.8 on 2025-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0037_add_rbac_permission_and_rbac_group_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="rbacgrouppermission",
            name="group_id",
            field=models.UUIDField(
                blank=True,
                help_text="The GUID associated with this particular group.",
                null=True,
            ),
        ),
    ]
