# Generated by Django 5.1.8 on 2025-04-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0038_add_group_id_field_to_rbac_group_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rbacpermission",
            name="sub_theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_theme_permissions",
                to="data.subtheme",
            ),
        ),
        migrations.AlterField(
            model_name="rbacpermission",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theme_permissions",
                to="data.theme",
            ),
        ),
    ]
