# Generated by Django 5.1.8 on 2025-04-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0038_set_theme_and_sub_theme_as_optional_on_rbac_permission"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rbacpermission",
            name="unique_permission_fields",
        ),
        migrations.RemoveField(
            model_name="rbacpermission",
            name="age",
        ),
        migrations.RemoveField(
            model_name="rbacpermission",
            name="stratum",
        ),
        migrations.AddConstraint(
            model_name="rbacpermission",
            constraint=models.UniqueConstraint(
                fields=(
                    "theme",
                    "sub_theme",
                    "topic",
                    "metric",
                    "geography_type",
                    "geography",
                ),
                name="unique_permission_fields",
            ),
        ),
    ]
