# Generated by Django 5.2.9 on 2026-01-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0040_remove_age_and_stratum_from_rbac_permission"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apitimeseries",
            index=models.Index(
                fields=["-date", "-id"], name="apitimeseries_date_id_idx"
            ),
        ),
    ]
