# Generated by Django 5.2.9 on 2025-12-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0040_remove_age_and_stratum_from_rbac_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreheadline",
            name="lower_confidence",
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name="coreheadline",
            name="upper_confidence",
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True),
        ),
    ]
