# Generated by Django 5.2.9 on 2025-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0040_remove_age_and_stratum_from_rbac_permission"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coreheadline",
            name="The `CoreHeadline` record should be unique if `force_write` is False",
        ),
        migrations.AddField(
            model_name="coreheadline",
            name="lower_confidence",
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name="coreheadline",
            name="upper_confidence",
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AddConstraint(
            model_name="coreheadline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("force_write", False)),
                fields=(
                    "metric",
                    "geography",
                    "stratum",
                    "age",
                    "sex",
                    "period_start",
                    "period_end",
                    "upper_confidence",
                    "metric_value",
                    "lower_confidence",
                ),
                name="The `CoreHeadline` record should be unique if `force_write` is False",
            ),
        ),
    ]
