# Generated by Django 5.2.9 on 2025-12-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0040_remove_age_and_stratum_from_rbac_permission"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apitimeseries",
            name="The `APITimeSeries` record should be unique if `force_write` is False",
        ),
        migrations.RemoveConstraint(
            model_name="coreheadline",
            name="The `CoreHeadline` record should be unique if `force_write` is False",
        ),
        migrations.RemoveConstraint(
            model_name="coretimeseries",
            name="The `CoreTimeSeries` record should be unique if `force_write` is False",
        ),
        migrations.AddConstraint(
            model_name="apitimeseries",
            constraint=models.UniqueConstraint(
                condition=models.Q(("force_write", False)),
                fields=(
                    "metric",
                    "topic",
                    "theme",
                    "sub_theme",
                    "geography",
                    "geography_type",
                    "geography_code",
                    "stratum",
                    "age",
                    "sex",
                    "year",
                    "month",
                    "epiweek",
                    "date",
                    "metric_value",
                    "in_reporting_delay_period",
                    "embargo",
                ),
                name="The `APITimeSeries` record should be unique if `force_write` is False",
            ),
        ),
        migrations.AddConstraint(
            model_name="coreheadline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("force_write", False)),
                fields=(
                    "metric",
                    "geography",
                    "stratum",
                    "age",
                    "sex",
                    "period_start",
                    "period_end",
                    "metric_value",
                    "embargo",
                ),
                name="The `CoreHeadline` record should be unique if `force_write` is False",
            ),
        ),
        migrations.AddConstraint(
            model_name="coretimeseries",
            constraint=models.UniqueConstraint(
                condition=models.Q(("force_write", False)),
                fields=(
                    "metric",
                    "geography",
                    "stratum",
                    "age",
                    "sex",
                    "year",
                    "month",
                    "epiweek",
                    "date",
                    "metric_value",
                    "in_reporting_delay_period",
                    "embargo",
                ),
                name="The `CoreTimeSeries` record should be unique if `force_write` is False",
            ),
        ),
    ]
