# Generated by Django 5.2.15 on 2026-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0041_coreheadline_add_confidence_intervals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitimeseries",
            name="metric_value",
            field=models.FloatField(),
        ),
    ]
