# Generated by Django 5.2.9 on 2025-12-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0041_coretimeseries_lower_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreheadline",
            name="lower_confidence",
            field=models.DecimalField(
                decimal_places=4, default=None, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="coreheadline",
            name="upper_confidence",
            field=models.DecimalField(
                decimal_places=4, default=None, max_digits=11, null=True
            ),
        ),
    ]
