# Generated by Django 5.2.9 on 2025-12-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0041_remove_coreheadline_the_coreheadline_record_should_be_unique_if_force_write_is_false_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coreheadline",
            name="lower_confidence",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="coreheadline",
            name="upper_confidence",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=11, null=True
            ),
        ),
    ]
