# Generated by Django 5.2.9 on 2026-01-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0041_coreheadline_add_confidence_intervals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coretimeseries",
            name="lower_confidence",
        ),
        migrations.RemoveField(
            model_name="coretimeseries",
            name="upper_confidence",
        ),
    ]
