# Generated by Django 5.2.9 on 2025-12-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0041_coretimeseries_lower_confidence_and_more"),
        ("data", "0042_alter_coreheadline_lower_confidence_and_more"),
    ]

    operations = []
