# Generated by Django 5.2.9 on 2025-12-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0043_merge_20251218_1244"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coreheadline",
            name="The `CoreHeadline` record should be unique if `force_write` is False",
        ),
        migrations.AddConstraint(
            model_name="coreheadline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("force_write", False)),
                fields=(
                    "metric",
                    "geography",
                    "stratum",
                    "age",
                    "sex",
                    "period_start",
                    "period_end",
                    "metric_value",
                ),
                name="The `CoreHeadline` record should be unique if `force_write` is False",
            ),
        ),
    ]
