# Generated by Django 5.2.16 on 2026-08-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0043_alter_apitimeseries_metric_value_rename_second_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIHeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=50)),
                ("sub_theme", models.CharField(max_length=50)),
                ("topic", models.CharField(max_length=50)),
                ("metric", models.CharField(max_length=100)),
                ("metric_group", models.CharField(max_length=50, null=True)),
                ("geography", models.CharField(max_length=100)),
                ("geography_type", models.CharField(max_length=50)),
                ("geography_code", models.CharField(max_length=9, null=True)),
                ("stratum", models.CharField(max_length=50)),
                ("sex", models.CharField(max_length=3, null=True)),
                ("age", models.CharField(max_length=50, null=True)),
                ("period_start", models.DateTimeField(null=True)),
                ("period_end", models.DateTimeField(null=True)),
                ("refresh_date", models.DateTimeField(null=True)),
                ("embargo", models.DateTimeField(null=True)),
                ("metric_value", models.FloatField()),
                (
                    "upper_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=11, null=True
                    ),
                ),
                (
                    "lower_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=11, null=True
                    ),
                ),
                ("force_write", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "theme",
                            "sub_theme",
                            "topic",
                            "metric",
                            "metric_value",
                            "geography",
                            "geography_type",
                        ],
                        name="data_apihea_theme_d13b3b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("force_write", False)),
                        fields=(
                            "age",
                            "geography",
                            "geography_code",
                            "geography_type",
                            "metric",
                            "metric_value",
                            "period_end",
                            "period_start",
                            "sex",
                            "stratum",
                            "sub_theme",
                            "theme",
                            "topic",
                        ),
                        name="The `APIHeadline` record should be unique if `force_write` is False",
                    )
                ],
            },
        ),
    ]
