# Generated by Django 5.2.17 on 2026-10-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0044_data_migration_updated_icb_codes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coreheadline",
            name="The `CoreHeadline` record should be unique if `force_write` is False",
        ),
        migrations.AddConstraint(
            model_name="coreheadline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("force_write", False)),
                fields=(
                    "metric",
                    "geography",
                    "stratum",
                    "age",
                    "sex",
                    "period_start",
                    "period_end",
                    "metric_value",
                    "upper_confidence",
                    "lower_confidence",
                ),
                name="The `CoreHeadline` record should be unique if `force_write` is False",
            ),
        ),
    ]
