# Generated by Django 5.2.15 on 2026-09-22 15:27

from django.db import migrations, models


def populate_metric_is_public(apps, schema_editor):
    """
    Backfill is_public from the legacy OFF-SENS prefix.

    Historically metric visibility was inferred from the metric name.
    OFF-SENS-prefixed metrics were treated as non-public.
    """
    metric = apps.get_model("data", "Metric")

    metric.objects.filter(name__startswith="OFF-SENS").update(
        is_public=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0044_data_migration_updated_icb_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="is_public",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.RunPython(
            populate_metric_is_public,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="metric",
            name="is_public",
            field=models.BooleanField(default=True, null=False),
        ),
    ]
