api_permissions = [
    {
        "name": "permission1",
        "theme": "non-communicable",
        "sub_theme": "respiratory",
    },
    {
        "name": "permission2",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
    },
    {
        "name": "permission3",
        "theme": "non-communicable",
        "sub_theme": "respiratory",
        "topic": "asthma",
        "geography_type": "Nation",
        "geography": "England",
        "metric": "asthma_syndromic_emergencyDepartment_countsByDay",
        "age": "all",
        "stratum": "default",
    },
    {
        "name": "permission4",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
        "topic": "COVID-19",
        "geography_type": "Nation",
        "geography": "England",
        "metric": "COVID-19_cases_rateRollingMean",
        "age": "all",
        "stratum": "default",
    },
    {
        "name": "permission5",
        "theme": "infectious_disease",
        "sub_theme": "NON_EXISTING",
    },
    {
        "name": "permission6",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
        "topic": "NON_EXISTING",
    },
    {
        "name": "permission7",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
        "topic": "COVID-19",
        "geography_type": "NON_EXISTING",
    },
    {
        "name": "permission8",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
        "topic": "COVID-19",
        "geography_type": "Nation",
        "geography": "NON_EXISTING",
    },
    {
        "name": "permission9",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
        "topic": "COVID-19",
        "geography_type": "Nation",
        "geography": "England",
        "metric": "NON_EXISTING",
    },
    {
        "name": "permission10",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
        "topic": "COVID-19",
        "geography_type": "Nation",
        "geography": "England",
        "metric": "COVID-19_cases_rateRollingMean",
        "age": "NON_EXISTING",
    },
    {
        "name": "permission11",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
        "topic": "COVID-19",
        "geography_type": "Nation",
        "geography": "England",
        "metric": "COVID-19_cases_rateRollingMean",
        "age": "all",
        "stratum": "NON_EXISTING",
    },
]