core_timeseries_list = [
    {
        "metric_frequency": "D",
        "theme": "non-communicable",
        "sub_theme": "respiratory",
        "topic": "asthma",
        "geography_type": "Nation",
        "geography": "England",
        "metric": "asthma_syndromic_emergencyDepartment_countsByDay",
        "stratum": "default",
        "sex": "f",
        "age": "all",
        "year": 2023,
        "epiweek": 1,
        "date": "2023-01-15",
        "metric_value": 123.45,
        "in_reporting_delay_period": True,
        "is_private": True,
    },
    {
        "metric_frequency": "D",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
        "topic": "COVID-19",
        "geography_type": "Nation",
        "geography": "England",
        "metric": "COVID-19_cases_rateRollingMean",
        "stratum": "default",
        "sex": "f",
        "age": "all",
        "year": 2023,
        "epiweek": 1,
        "date": "2023-01-15",
        "metric_value": 123.45,
        "in_reporting_delay_period": True,
        "is_private": True,
    },
    {
        "metric_frequency": "D",
        "theme": "infectious_disease",
        "sub_theme": "respiratory",
        "topic": "COVID-19",
        "geography_type": "Nation",
        "geography": "England",
        "metric": "COVID-19_vaccinations_autumn23_dosesByDay",
        "stratum": "default",
        "sex": "f",
        "age": "all",
        "year": 2023,
        "epiweek": 1,
        "date": "2023-01-15",
        "metric_value": 123.45,
        "in_reporting_delay_period": True,
        "is_private": False,
    },
]
