# Generated by Django 4.2.7 on 2023-12-11 17:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("metrics_documentation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsDocumentationChildEntry",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.TextBlock(
                                                help_text="\nThe text you add here will be used as the heading for this section. \n",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                help_text="\nA required body of text to accompany this block.\n",
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                    ),
                ),
                ("date_posted", models.DateField()),
                ("page_description", models.TextField()),
                ("metric", models.CharField(max_length=255)),
                ("topic", models.CharField(default="", max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
