# Generated by Django 5.1.2 on 2024-11-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics_documentation", "0007_add_pagination_control_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metricsdocumentationchildentry",
            name="date_posted",
        ),
    ]
