# Generated by Django 5.1.2 on 2024-11-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics_documentation", "0007_add_pagination_control_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metricsdocumentationparentpage",
            name="related_links_layout",
        ),
        migrations.DeleteModel(
            name="MetricsDocumentationParentPageRelatedLinks",
        ),
    ]
