# Generated by Django 5.1.2 on 2024-11-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics_documentation",
            "0009_remove_metricsdocumentationparentpage_date_posted",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metricsdocumentationparentpage",
            name="related_links_layout",
        ),
        migrations.DeleteModel(
            name="MetricsDocumentationParentPageRelatedLinks",
        ),
    ]
