# Generated by Django 5.2.9 on 2026-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics_documentation", "0011_add_single_page_announcements"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsdocumentationchildentry",
            name="enable_public_page",
            field=models.BooleanField(default=True),
            preserve_default=False
        ),
    ]
