# Generated by Django 5.2.9 on 2026-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics_documentation", "0011_add_single_page_announcements"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsdocumentationchildentry",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="enable public page"),
            preserve_default=False,
        ),
    ]
