# Generated by Django 5.1.7 on 2025-05-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics_documentation", "0011_add_single_page_announcement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metricsdocumentationparentpageannouncement",
            name="page",
        ),
        migrations.DeleteModel(
            name="MetricsDocumentationChildPageAnnouncement",
        ),
        migrations.DeleteModel(
            name="MetricsDocumentationParentPageAnnouncement",
        ),
    ]
