# Generated by Django 5.2.9 on 2026-01-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics_documentation",
            "0012_metricsdocumentationchildentry_enable_public_page",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricsdocumentationchildentry",
            name="enable_public_page",
            field=models.BooleanField(default=False),
        ),
    ]
