# Generated by Django 5.2.9 on 2026-02-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics_documentation", "0012_metricsdocumentationchildentry_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricsdocumentationchildentry",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="enable public page"),
        ),
    ]
