# Generated by Django 5.1.7 on 2025-04-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics_documentation",
            "0012_alter_metricsdocumentationchildpageannouncement_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metricsdocumentationchildpageannouncement",
            name="badge",
        ),
        migrations.RemoveField(
            model_name="metricsdocumentationparentpageannouncement",
            name="badge",
        ),
    ]
