# Generated by Django 5.1.7 on 2025-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics_documentation",
            "0013_remove_metricsdocumentationchildpageannouncement_badge_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metricsdocumentationchildpageannouncement",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="metricsdocumentationparentpageannouncement",
            options={"base_manager_name": "objects"},
        ),
    ]
