# Generated by Django 5.1.7 on 2025-05-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics_documentation",
            "0014_alter_metricsdocumentationchildpageannouncement_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metricsdocumentationchildpageannouncement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="metricsdocumentationparentpageannouncement",
            options={},
        ),
    ]
