# Generated by Django 5.2.13 on 2026-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics_documentation",
            "0015_alter_metricsdocumentationchildentry_page_classification",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsdocumentationchildentry",
            name="sub_theme",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="metricsdocumentationchildentry",
            name="theme",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
