# Generated by Django 5.2.13 on 2026-05-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics_documentation",
            "0016_metricsdocumentationchildentry_sub_theme_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="metricsdocumentationchildentry",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
