# Generated by Django 5.2.17 on 2026-09-20 19:14

from django.db import migrations, models
from django.db.models import F


def get_metric_id_to_name_mapping(metric_model) -> dict[str, str]:
    return {str(metric.id): metric.name for metric in metric_model.objects.all()}


def get_metric_name_to_topic_id_mapping(metric_model) -> dict[str, int]:
    return {metric.name: metric.topic.id for metric in metric_model.objects.all()}


def forwards(apps, schema_editor):
    """
    Forward data migration.

    Args:
        apps: the apps object to get the models from
        schema_editor: the schema_editor object
    """
    MetricsDocumentationChildEntry = apps.get_model(
        "metrics_documentation", "MetricsDocumentationChildEntry"
    )
    Metric = apps.get_model("data", "Metric")

    # if the page is public, set all the fields to the empty string
    MetricsDocumentationChildEntry.objects.filter(is_public=True).update(
        page_theme="",
        page_sub_theme="",
        page_topic="",
        page_classification="",
    )

    # for non-public pages, copy the theme, sub-theme, and topic values directly
    MetricsDocumentationChildEntry.objects.filter(is_public=False).update(
        page_theme=F("theme"),
        page_sub_theme=F("sub_theme"),
        page_topic=F("topic"),
    )

    # for both public and non-public pages, set the topic and the metric with some additional logic
    metric_id_to_name_mapping = get_metric_id_to_name_mapping(Metric)
    metric_name_to_topic_id_mapping = get_metric_name_to_topic_id_mapping(Metric)
    # we're going to do updates during the loop so we need to get all the objects upfront to avoid errors but we only
    # need certain fields so just grab them specifically
    child_entries = list(
        MetricsDocumentationChildEntry.objects.only("id", "metric", "page_topic").all()
    )
    for child in child_entries:
        # if the metric is an ID instead of a name it'll be in the ID map so we can replace it. If it's a name we just
        # leave it be and it can't be null
        if child.metric in metric_id_to_name_mapping:
            child.metric = metric_id_to_name_mapping[child.metric]
        # if the page_topic is null, replace it with the correct topic ID. There's no way the topic could be a name and
        # if it's an ID we just leave it be, hence we only check for nulls here
        if child.page_topic is None:
            child.page_topic = metric_name_to_topic_id_mapping[child.metric]
        child.save()


class Migration(migrations.Migration):

    dependencies = [
        ("metrics_documentation", "0017_alter_metricsdocumentationchildentry_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsdocumentationchildentry",
            name="page_sub_theme",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="metricsdocumentationchildentry",
            name="page_theme",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="metricsdocumentationchildentry",
            name="page_topic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="metricsdocumentationchildentry",
            name="page_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("official", "Official"),
                    ("official_sensitive", "Official Sensitive"),
                    ("protective_marking_not_set", "Protective Marking Not Set"),
                    ("secret", "Secret"),
                    ("top_secret", "Top Secret"),
                ],
                default="",
                help_text="\nThe classification level of all data on this page (only applies to non-public pages). Defaults to `Official-Sensitive`.\n",
                max_length=50,
            ),
        ),
        migrations.RunPython(code=forwards, reverse_code=migrations.RunPython.noop),
    ]
