# Generated by Django 5.2.17 on 2026-09-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics_documentation",
            "0018_metricsdocumentationchildentry_page_sub_theme_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metricsdocumentationchildentry",
            name="sub_theme",
        ),
        migrations.RemoveField(
            model_name="metricsdocumentationchildentry",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="metricsdocumentationchildentry",
            name="topic",
        ),
    ]
