# Generated by Django 4.2.4 on 2023-09-07 17:54

import wagtail.blocks
import wagtail.fields
from django.db import migrations

import cms.metrics_interface.field_choices_callables


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_add_page_description_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        help_text="\nThe text you add here will be used as the heading for this section. \n",
                                        required=True,
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "text_card",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                features=[
                                                                    "h2",
                                                                    "h3",
                                                                    "h4",
                                                                    "bold",
                                                                    "ul",
                                                                    "link",
                                                                ],
                                                                help_text="\nThis section of text will comprise this card. \nNote that this card will span the length of the available page width if sufficient text content is provided.\n",
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "chart_row_card",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "columns",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "chart_card",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "title",
                                                                                    wagtail.blocks.TextBlock(
                                                                                        help_text="\nThe title to display for this component. \nNote that this will be shown in the hex colour #505A5F\n",
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "body",
                                                                                    wagtail.blocks.TextBlock(
                                                                                        help_text="\nAn optional body of text to accompany this block.\n",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "x_axis",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        choices=cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                                                                                        help_text="\nAn optional choice of what to display along the x-axis of the chart.\nIf nothing is provided, `dates` will be used by default.\nDates are used by default\n",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "y_axis",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        choices=cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                                                                                        help_text="\nAn optional choice of what to display along the y-axis of the chart.\nIf nothing is provided, `metric value` will be used by default.\n",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "chart",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "plot",
                                                                                                wagtail.blocks.StructBlock(
                                                                                                    [
                                                                                                        (
                                                                                                            "topic",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_topic_names,
                                                                                                                help_text="The name of the topic to pull data e.g. COVID-19.",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_metric_names,
                                                                                                                help_text='\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "chart_type",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_chart_types,
                                                                                                                help_text="\nThe name of the type of chart which you want to create e.g. waffle\n",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "date_from",
                                                                                                            wagtail.blocks.DateBlock(
                                                                                                                help_text="\nThe date from which to begin the supporting plot data. \nNote that if nothing is provided, a default of 1 year ago from the current date will be applied.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "date_to",
                                                                                                            wagtail.blocks.DateBlock(
                                                                                                                help_text="\nThe date to which to end the supporting plot data. \nNote that if nothing is provided, a default of the current date will be applied.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "stratum",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_stratum_names,
                                                                                                                help_text="\nThe smallest subgroup a piece of data can be broken down into.\nFor example, this could be broken down by ethnicity or testing pillar.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "geography",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_geography_names,
                                                                                                                help_text="\nThe name of the geography associated with this particular piece of data.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "geography_type",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_geography_type_names,
                                                                                                                help_text="\nThe type of geographical categorisation to apply any data filtering to.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "sex",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_sex_names,
                                                                                                                help_text="\nThe gender to filter for, if any.\nThe only options available are `M`, `F` and `ALL`.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "age",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_age_names,
                                                                                                                help_text="\nThe age band to filter for, if any.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "label",
                                                                                                            wagtail.blocks.TextBlock(
                                                                                                                help_text="\nThe label to assign on the legend for this individual plot.\nE.g. `15 to 44 years old`\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "line_colour",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_colours,
                                                                                                                help_text='\nThe colour to apply to this individual line plot. The colours conform to the GDS specification.\nCurrently, only the `line_multi_coloured` chart type supports different line colours.\nFor all other chart types, this field will be ignored.\nNote that if nothing is provided, a default of "BLACK" will be applied.\nE.g. `GREEN`\n',
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "line_type",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_chart_line_types,
                                                                                                                help_text='\nThe line type to apply to this individual line plot.\nCurrently, only the `line_multi_coloured` chart type supports different line types.\nFor all other chart types, this field will be ignored.\nNote that if nothing is provided, a default of "SOLID" will be applied.\nE.g. `DASH`\n',
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                    ]
                                                                                                ),
                                                                                            )
                                                                                        ],
                                                                                        help_text="\nAdd the plots required for your chart. \nWithin each plot, you will be required to add a set of fields which will be used to fetch the supporting data \nfor that plot.\n",
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "chart_with_headline_and_trend_card",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "title",
                                                                                    wagtail.blocks.TextBlock(
                                                                                        help_text="\nThe title to display for this component. \nNote that this will be shown in the hex colour #505A5F\n",
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "body",
                                                                                    wagtail.blocks.TextBlock(
                                                                                        help_text="\nAn optional body of text to accompany this block.\n",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "x_axis",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        choices=cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                                                                                        help_text="\nAn optional choice of what to display along the x-axis of the chart.\nIf nothing is provided, `dates` will be used by default.\nDates are used by default\n",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "y_axis",
                                                                                    wagtail.blocks.ChoiceBlock(
                                                                                        choices=cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                                                                                        help_text="\nAn optional choice of what to display along the y-axis of the chart.\nIf nothing is provided, `metric value` will be used by default.\n",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "chart",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "plot",
                                                                                                wagtail.blocks.StructBlock(
                                                                                                    [
                                                                                                        (
                                                                                                            "topic",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_topic_names,
                                                                                                                help_text="The name of the topic to pull data e.g. COVID-19.",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_metric_names,
                                                                                                                help_text='\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "chart_type",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_chart_types,
                                                                                                                help_text="\nThe name of the type of chart which you want to create e.g. waffle\n",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "date_from",
                                                                                                            wagtail.blocks.DateBlock(
                                                                                                                help_text="\nThe date from which to begin the supporting plot data. \nNote that if nothing is provided, a default of 1 year ago from the current date will be applied.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "date_to",
                                                                                                            wagtail.blocks.DateBlock(
                                                                                                                help_text="\nThe date to which to end the supporting plot data. \nNote that if nothing is provided, a default of the current date will be applied.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "stratum",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_stratum_names,
                                                                                                                help_text="\nThe smallest subgroup a piece of data can be broken down into.\nFor example, this could be broken down by ethnicity or testing pillar.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "geography",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_geography_names,
                                                                                                                help_text="\nThe name of the geography associated with this particular piece of data.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "geography_type",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_geography_type_names,
                                                                                                                help_text="\nThe type of geographical categorisation to apply any data filtering to.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "sex",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_sex_names,
                                                                                                                help_text="\nThe gender to filter for, if any.\nThe only options available are `M`, `F` and `ALL`.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "age",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_age_names,
                                                                                                                help_text="\nThe age band to filter for, if any.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "label",
                                                                                                            wagtail.blocks.TextBlock(
                                                                                                                help_text="\nThe label to assign on the legend for this individual plot.\nE.g. `15 to 44 years old`\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "line_colour",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_colours,
                                                                                                                help_text='\nThe colour to apply to this individual line plot. The colours conform to the GDS specification.\nCurrently, only the `line_multi_coloured` chart type supports different line colours.\nFor all other chart types, this field will be ignored.\nNote that if nothing is provided, a default of "BLACK" will be applied.\nE.g. `GREEN`\n',
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "line_type",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_chart_line_types,
                                                                                                                help_text='\nThe line type to apply to this individual line plot.\nCurrently, only the `line_multi_coloured` chart type supports different line types.\nFor all other chart types, this field will be ignored.\nNote that if nothing is provided, a default of "SOLID" will be applied.\nE.g. `DASH`\n',
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                    ]
                                                                                                ),
                                                                                            )
                                                                                        ],
                                                                                        help_text="\nAdd the plots required for your chart. \nWithin each plot, you will be required to add a set of fields which will be used to fetch the supporting data \nfor that plot.\n",
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "headline_number_columns",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "headline_number",
                                                                                                wagtail.blocks.StructBlock(
                                                                                                    [
                                                                                                        (
                                                                                                            "topic",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_topic_names,
                                                                                                                help_text="The name of the topic to pull data e.g. COVID-19.",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_metric_names,
                                                                                                                help_text='\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "body",
                                                                                                            wagtail.blocks.TextBlock(
                                                                                                                help_text="\nAn optional body of text to accompany this block.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                    ],
                                                                                                    help_text='\nThis component will display a key headline number type metric.\nYou can also optionally add a body of text to accompany that headline number.\nE.g. "Patients admitted"\n',
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "trend_number",
                                                                                                wagtail.blocks.StructBlock(
                                                                                                    [
                                                                                                        (
                                                                                                            "topic",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_topic_names,
                                                                                                                help_text="The name of the topic to pull data e.g. COVID-19.",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_change_type_metric_names,
                                                                                                                help_text="\nThe name of the trend type metric to pull data e.g. \"COVID-19_headline_ONSdeaths_7daychange\". \nNote that only 'change' type metrics are available for selection for this field type.\n",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "body",
                                                                                                            wagtail.blocks.TextBlock(
                                                                                                                help_text="\nAn optional body of text to accompany this block.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "percentage_metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_percent_change_type_names,
                                                                                                                help_text="\nThe name of the accompanying percentage trend type metric to pull data \ne.g. \"COVID-19_headline_ONSdeaths_7daypercentchange\". \nNote that only 'percent' type metrics are available for selection for this field type.\n",
                                                                                                            ),
                                                                                                        ),
                                                                                                    ],
                                                                                                    help_text='\nThis component will display a trend number type metric.\nThis will display an arrow pointing in the direction of the metric change \nas well as colouring of the block to indicate the context of the change.\nYou can also optionally add a body of text to accompany that headline number.\nE.g. "Last 7 days"\n',
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "percentage_number",
                                                                                                wagtail.blocks.StructBlock(
                                                                                                    [
                                                                                                        (
                                                                                                            "topic",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_topic_names,
                                                                                                                help_text="The name of the topic to pull data e.g. COVID-19.",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_metric_names,
                                                                                                                help_text='\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "body",
                                                                                                            wagtail.blocks.TextBlock(
                                                                                                                help_text="\nAn optional body of text to accompany this block.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                    ],
                                                                                                    help_text='\nThis component will display a percentage number type metric.\nThis will display the value of the metric appended with a % character.\nYou can also optionally add a body of text to accompany this percentage number.\nE.g. "Virus tests positivity".\n',
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        help_text="\nAdd up to 2 headline or trend number column components within this space.\nNote that these figures will be displayed within the card, and above the chart itself.\n",
                                                                                        max_num=2,
                                                                                        min_num=0,
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    ),
                                                                ],
                                                                help_text="\nHere you can add 1 or 2 columns to contain a particular chart card.\nIf you add the 1 column, then the chart card will spread across the available width.\nIf you add 2 columns, then the cards will be split across 2 columns within the available width.\n",
                                                                max_num=2,
                                                                min_num=1,
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "headline_numbers_row_card",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "columns",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "column",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "title",
                                                                                    wagtail.blocks.TextBlock(
                                                                                        help_text="\nThe title to display for this component. \nNote that this will be shown in the hex colour #505A5F\n",
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "rows",
                                                                                    wagtail.blocks.StreamBlock(
                                                                                        [
                                                                                            (
                                                                                                "headline_number",
                                                                                                wagtail.blocks.StructBlock(
                                                                                                    [
                                                                                                        (
                                                                                                            "topic",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_topic_names,
                                                                                                                help_text="The name of the topic to pull data e.g. COVID-19.",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_metric_names,
                                                                                                                help_text='\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "body",
                                                                                                            wagtail.blocks.TextBlock(
                                                                                                                help_text="\nAn optional body of text to accompany this block.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                    ],
                                                                                                    help_text='\nThis component will display a key headline number type metric.\nYou can also optionally add a body of text to accompany that headline number.\nE.g. "Patients admitted"\n',
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "trend_number",
                                                                                                wagtail.blocks.StructBlock(
                                                                                                    [
                                                                                                        (
                                                                                                            "topic",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_topic_names,
                                                                                                                help_text="The name of the topic to pull data e.g. COVID-19.",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_change_type_metric_names,
                                                                                                                help_text="\nThe name of the trend type metric to pull data e.g. \"COVID-19_headline_ONSdeaths_7daychange\". \nNote that only 'change' type metrics are available for selection for this field type.\n",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "body",
                                                                                                            wagtail.blocks.TextBlock(
                                                                                                                help_text="\nAn optional body of text to accompany this block.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "percentage_metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_percent_change_type_names,
                                                                                                                help_text="\nThe name of the accompanying percentage trend type metric to pull data \ne.g. \"COVID-19_headline_ONSdeaths_7daypercentchange\". \nNote that only 'percent' type metrics are available for selection for this field type.\n",
                                                                                                            ),
                                                                                                        ),
                                                                                                    ],
                                                                                                    help_text='\nThis component will display a trend number type metric.\nThis will display an arrow pointing in the direction of the metric change \nas well as colouring of the block to indicate the context of the change.\nYou can also optionally add a body of text to accompany that headline number.\nE.g. "Last 7 days"\n',
                                                                                                ),
                                                                                            ),
                                                                                            (
                                                                                                "percentage_number",
                                                                                                wagtail.blocks.StructBlock(
                                                                                                    [
                                                                                                        (
                                                                                                            "topic",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_topic_names,
                                                                                                                help_text="The name of the topic to pull data e.g. COVID-19.",
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "metric",
                                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                                choices=cms.metrics_interface.field_choices_callables.get_all_unique_metric_names,
                                                                                                                help_text='\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                                                                                                            ),
                                                                                                        ),
                                                                                                        (
                                                                                                            "body",
                                                                                                            wagtail.blocks.TextBlock(
                                                                                                                help_text="\nAn optional body of text to accompany this block.\n",
                                                                                                                required=False,
                                                                                                            ),
                                                                                                        ),
                                                                                                    ],
                                                                                                    help_text='\nThis component will display a percentage number type metric.\nThis will display the value of the metric appended with a % character.\nYou can also optionally add a body of text to accompany this percentage number.\nE.g. "Virus tests positivity".\n',
                                                                                                ),
                                                                                            ),
                                                                                        ],
                                                                                        help_text="\nHere you can add up to 2 rows within this column component.\nEach row can be used to add a number block. \nThis can be a headline number, a trend number or a percentage number.\nIf you only add 1 row, then that block will be rendered on the upper half of the column.\nAnd the bottom row of the column will remain empty.\n",
                                                                                        max_num=2,
                                                                                        min_num=1,
                                                                                        required=True,
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    )
                                                                ],
                                                                help_text="\nAdd up to 5 number column components within this row. \nThe columns are ordered from left to right, top to bottom respectively. \nSo by moving 1 column component above the other, that component will be rendered in the column left of the other. \n",
                                                                max_num=5,
                                                                min_num=1,
                                                            ),
                                                        )
                                                    ]
                                                ),
                                            ),
                                        ],
                                        help_text="\nHere you can add any number of content row cards for this section.\nNote that these cards will be displayed across the available width.\n",
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
