# Generated by Django 4.2.4 on 2023-09-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagerelatedlink",
            name="url",
            field=models.URLField(max_length=400, verbose_name="URL"),
        ),
    ]
