# Generated by Django 5.1 on 2024-08-29 11:11

import cms.metrics_interface.field_choices_callables
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_add_ukhsa_root_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="related_links_layout",
            field=models.CharField(
                choices=[("Sidebar", "Sidebar"), ("Footer", "Footer")],
                default="Footer",
                help_text="\nThis dictates where the related links for this page will be positioned.\n",
                max_length=10,
                verbose_name="Layout",
            ),
        )
    ]
