# Generated by Django 5.1.1 on 2024-09-30 10:40

import cms.dynamic_content.cards
import cms.metrics_interface.field_choices_callables
import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_homepage_body"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_change_frequency",
                    models.IntegerField(
                        choices=[
                            (1, "Always"),
                            (2, "Hourly"),
                            (3, "Daily"),
                            (4, "Weekly"),
                            (5, "Monthly"),
                            (6, "Yearly"),
                            (7, "Never"),
                        ],
                        default=5,
                        help_text="<p>This value tells search engines how often a page’s content updates, offering a hint for crawling prioritization.</p>\n<p><strong>Always</strong>: This means the page is constantly changing with important, up-to-the-minute updates. \nA subreddit index page, a stock market data page, and the index page of a major news site might use this tag.</p>\n<p><strong>Hourly</strong>: The page is updated on an hourly basis or thereabouts.\n Major news sites, weather sites, and active web forums might use this tag.</p>\n<p><strong>Daily</strong>: The page is updated with new content on average once a day. \nSmall web forums, classified ad pages, daily newspapers, and daily blogs might use this tag for their homepage.</p>\n<p><strong>Weekly</strong>: The page is updated around once a week with new content. \nProduct info pages with daily pricing information, small blogs, and website directories use this tag.</p>\n<p><strong>Monthly</strong>: The page is updated around once a month; maybe more, maybe less. \nCategory pages, evergreen guides with updated information, and FAQs often use this tag.</p>\n<p><strong>Yearly</strong>: The page is rarely updated but may receive updates once or twice a year. \nMany static pages, such as registration pages, About pages, and privacy policies, fall into this category.</p>\n<p><strong>Never</strong>: The page is never going to be updated. \nOld blog entries, old news stories, and completely static pages fall into this category. </p>",
                        verbose_name="SEO change frequency",
                    ),
                ),
                (
                    "seo_priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.5,
                        help_text="\nThis value signals the importance of a page to search engines. \nAssigning accurate priority values to key pages of your site can help search engines understand \nthe structure and hierarchy of your content.\nThis must be a number between 0.1 - 1.0.\n",
                        max_digits=2,
                        validators=[
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                            django.core.validators.MinValueValidator(Decimal("0.1")),
                        ],
                        verbose_name="SEO priority",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("section", 59)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "\nThe text you add here will be used as the heading for this section. \n",
                                    "required": True,
                                },
                            ),
                            1: (
                                "cms.dynamic_content.blocks.PageLinkChooserBlock",
                                (),
                                {
                                    "help_text": "\nThe related index page you want to link to. Eg: `Respiratory viruses` or `Outbreaks`\n",
                                    "page_type": ["composite.CompositePage"],
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "ul",
                                        "link",
                                    ],
                                    "help_text": "\nThis section of text will comprise this card. \nNote that this card will span the length of the available page width if sufficient text content is provided.\n",
                                },
                            ),
                            3: ("wagtail.blocks.StructBlock", [[("body", 2)]], {}),
                            4: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "\nThe title to display for this component. \nNote that this will be shown in the hex colour #505A5F\n",
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "\nAn optional body of text to accompany this block.\n",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "\nThe ID to associate with this component. \nThis allows for tracking of events when users interact with this component.\nNote that changing this multiple times will result in the recording of different groups of events.\n",
                                    "label": "Tag manager event ID",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                                    "help_text": "\nAn optional choice of what to display along the x-axis of the chart.\nIf nothing is provided, `dates` will be used by default.\nDates are used by default\n",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                                    "help_text": "\nAn optional choice of what to display along the y-axis of the chart.\nIf nothing is provided, `metric value` will be used by default.\n",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_topic_names,
                                    "help_text": "The name of the topic to pull data e.g. COVID-19.",
                                },
                            ),
                            10: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_timeseries_metric_names,
                                    "help_text": '\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_geography_names,
                                    "help_text": "\nThe name of the geography associated with this particular piece of data.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                                },
                            ),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_geography_type_names,
                                    "help_text": "\nThe type of geographical categorisation to apply any data filtering to.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                                },
                            ),
                            13: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_sex_names,
                                    "help_text": "\nThe gender to filter for, if any.\nThe only options available are `M`, `F` and `ALL`.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n",
                                },
                            ),
                            14: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_age_names,
                                    "help_text": "\nThe age band to filter for, if any.\nBy default, no filtering will be applied to the underlying query if no selection is made.\n",
                                },
                            ),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_stratum_names,
                                    "help_text": "\nThe smallest subgroup a piece of data can be broken down into.\nFor example, this could be broken down by ethnicity or testing pillar.\nIf nothing is provided, then no filtering will be applied for this field.\n",
                                },
                            ),
                            16: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_chart_types,
                                    "help_text": "\nThe name of the type of chart which you want to create e.g. waffle\n",
                                },
                            ),
                            17: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "\nThe date from which to begin the supporting plot data. \nNote that if nothing is provided, a default of 1 year ago from the current date will be applied.\n",
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "\nThe date to which to end the supporting plot data. \nNote that if nothing is provided, a default of the current date will be applied.\n",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "\nThe label to assign on the legend for this individual plot.\nE.g. `15 to 44 years old`\n",
                                    "required": False,
                                },
                            ),
                            20: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_colours,
                                    "help_text": '\nThe colour to apply to this individual line plot. The colours conform to the GDS specification.\nCurrently, only the `line_multi_coloured` chart type supports different line colours.\nFor all other chart types, this field will be ignored.\nNote that if nothing is provided, a default of "BLACK" will be applied.\nE.g. `GREEN`\n',
                                },
                            ),
                            21: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_chart_line_types,
                                    "help_text": '\nThe line type to apply to this individual line plot.\nCurrently, only the `line_multi_coloured` chart type supports different line types.\nFor all other chart types, this field will be ignored.\nNote that if nothing is provided, a default of "SOLID" will be applied.\nE.g. `DASH`\n',
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "\nIf set to true, markers are drawn on each individual data point.\nIf set to false, markers are not drawn at all.\nThis is only applicable to line-type charts.\n",
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "\nIf set to true, draws the plot as a spline line, resulting in smooth curves between data points.\nIf set to false, draws the plot as a linear line, \nresulting in linear point-to-point lines being drawn between data points.\nThis is only applicable to line-type charts.\n",
                                    "required": False,
                                },
                            ),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("topic", 9),
                                        ("metric", 10),
                                        ("geography", 11),
                                        ("geography_type", 12),
                                        ("sex", 13),
                                        ("age", 14),
                                        ("stratum", 15),
                                        ("chart_type", 16),
                                        ("date_from", 17),
                                        ("date_to", 18),
                                        ("label", 19),
                                        ("line_colour", 20),
                                        ("line_type", 21),
                                        ("use_markers", 22),
                                        ("use_smooth_lines", 23),
                                    ]
                                ],
                                {},
                            ),
                            25: (
                                "wagtail.blocks.StreamBlock",
                                [[("plot", 24)]],
                                {
                                    "help_text": "\nAdd the plots required for your chart. \nWithin each plot, you will be required to add a set of fields which will be used to fetch the supporting data \nfor that plot.\n"
                                },
                            ),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 4),
                                        ("body", 5),
                                        ("tag_manager_event_id", 6),
                                        ("x_axis", 7),
                                        ("y_axis", 8),
                                        ("chart", 25),
                                    ]
                                ],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                                    "help_text": "\nA required choice of what to display along the x-axis of the chart.\n",
                                },
                            ),
                            28: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_headline_metric_names,
                                    "help_text": '\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                                },
                            ),
                            29: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_headline_chart_types,
                                    "help_text": "\nThe name of the type of chart which you want to create e.g. waffle\n",
                                },
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("topic", 9),
                                        ("metric", 28),
                                        ("geography", 11),
                                        ("geography_type", 12),
                                        ("sex", 13),
                                        ("age", 14),
                                        ("stratum", 15),
                                        ("chart_type", 29),
                                        ("line_colour", 20),
                                        ("label", 19),
                                    ]
                                ],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.StreamBlock",
                                [[("plot", 30)]],
                                {
                                    "help_texts": "\nAdd the plots required for your chart. \nWithin each plot, you will be required to add a set of fields which will be used to fetch the supporting data \nfor that plot.\n"
                                },
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 4),
                                        ("body", 5),
                                        ("tag_manager_event_id", 6),
                                        ("x_axis", 27),
                                        ("y_axis", 8),
                                        ("chart", 31),
                                    ]
                                ],
                                {},
                            ),
                            33: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_unique_metric_names,
                                    "help_text": '\nThe name of the metric to pull data for e.g. "COVID-19_deaths_ONSByDay".\n',
                                },
                            ),
                            34: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("topic", 9),
                                        ("metric", 33),
                                        ("geography", 11),
                                        ("geography_type", 12),
                                        ("sex", 13),
                                        ("age", 14),
                                        ("stratum", 15),
                                        ("body", 5),
                                    ]
                                ],
                                {
                                    "help_text": '\nThis component will display a key headline number type metric.\nYou can also optionally add a body of text to accompany that headline number.\nE.g. "Patients admitted"\n'
                                },
                            ),
                            35: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_unique_change_type_metric_names,
                                    "help_text": "\nThe name of the trend type metric to pull data e.g. \"COVID-19_headline_ONSdeaths_7daychange\". \nNote that only 'change' type metrics are available for selection for this field type.\n",
                                },
                            ),
                            36: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_all_unique_percent_change_type_names,
                                    "help_text": "\nThe name of the accompanying percentage trend type metric to pull data \ne.g. \"COVID-19_headline_ONSdeaths_7daypercentchange\". \nNote that only 'percent' type metrics are available for selection for this field type.\n",
                                },
                            ),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("topic", 9),
                                        ("metric", 35),
                                        ("geography", 11),
                                        ("geography_type", 12),
                                        ("sex", 13),
                                        ("age", 14),
                                        ("stratum", 15),
                                        ("body", 5),
                                        ("percentage_metric", 36),
                                    ]
                                ],
                                {
                                    "help_text": '\nThis component will display a trend number type metric.\nThis will display an arrow pointing in the direction of the metric change \nas well as colouring of the block to indicate the context of the change.\nYou can also optionally add a body of text to accompany that headline number.\nE.g. "Last 7 days"\n'
                                },
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("topic", 9),
                                        ("metric", 33),
                                        ("geography", 11),
                                        ("geography_type", 12),
                                        ("sex", 13),
                                        ("age", 14),
                                        ("stratum", 15),
                                        ("body", 5),
                                    ]
                                ],
                                {
                                    "help_text": '\nThis component will display a percentage number type metric.\nThis will display the value of the metric appended with a % character.\nYou can also optionally add a body of text to accompany this percentage number.\nE.g. "Virus tests positivity".\n'
                                },
                            ),
                            39: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("headline_number", 34),
                                        ("trend_number", 37),
                                        ("percentage_number", 38),
                                    ]
                                ],
                                {
                                    "help_text": "\nAdd up to 2 headline or trend number column components within this space.\nNote that these figures will be displayed within the card, and above the chart itself.\n",
                                    "max_num": 2,
                                    "min_num": 0,
                                    "required": False,
                                },
                            ),
                            40: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 4),
                                        ("body", 5),
                                        ("tag_manager_event_id", 6),
                                        ("x_axis", 7),
                                        ("y_axis", 8),
                                        ("chart", 25),
                                        ("headline_number_columns", 39),
                                    ]
                                ],
                                {},
                            ),
                            41: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "\nThe sub title to display for this component.\n",
                                    "required": False,
                                },
                            ),
                            42: (
                                "cms.dynamic_content.blocks.PageLinkChooserBlock",
                                (),
                                {
                                    "help_text": "\nThe related topic page you want to link to. Eg: `COVID-19`\n",
                                    "page_type": ["topic.TopicPage"],
                                    "required": True,
                                },
                            ),
                            43: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                                    "help_text": "\nA required choice of what to display along the x-axis of the chart.\n",
                                    "ready_only": True,
                                },
                            ),
                            44: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_possible_axis_choices,
                                    "help_text": "\nA required choice of what to display along the y-axis of the chart.\n",
                                },
                            ),
                            45: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.metrics_interface.field_choices_callables.get_simplified_chart_types
                                },
                            ),
                            46: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("topic", 9),
                                        ("metric", 10),
                                        ("geography", 11),
                                        ("geography_type", 12),
                                        ("sex", 13),
                                        ("age", 14),
                                        ("stratum", 15),
                                        ("chart_type", 45),
                                    ]
                                ],
                                {},
                            ),
                            47: (
                                "wagtail.blocks.StreamBlock",
                                [[("plot", 46)]],
                                {
                                    "help_text": "\nAdd the plots required for your chart. \nWithin each plot, you will be required to add a set of fields which will be used to fetch the supporting data \nfor that plot.\n",
                                    "max_num": 1,
                                    "required": True,
                                },
                            ),
                            48: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 4),
                                        ("sub_title", 41),
                                        ("tag_manager_event_id", 6),
                                        ("topic_page", 42),
                                        ("x_axis", 43),
                                        ("y_axis", 44),
                                        ("chart", 47),
                                    ]
                                ],
                                {},
                            ),
                            49: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("chart_card", 26),
                                        ("headline_chart_card", 32),
                                        ("chart_with_headline_and_trend_card", 40),
                                        ("simplified_chart_with_link", 48),
                                    ]
                                ],
                                {
                                    "help_text": "\nHere you can add chart cards to a section and the layout will change based on the number of cards added.\nA single card will expand to take up half the row. When 2 or 3 cards are added they will share the width\nof a row equally, creating either a 2 or 3 column layout.\n",
                                    "min_num": 1,
                                },
                            ),
                            50: ("wagtail.blocks.StructBlock", [[("cards", 49)]], {}),
                            51: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("headline_number", 34),
                                        ("trend_number", 37),
                                        ("percentage_number", 38),
                                    ]
                                ],
                                {
                                    "help_text": "\nHere you can add up to 2 rows within this column component.\nEach row can be used to add a number block. \nThis can be a headline number, a trend number or a percentage number.\nIf you only add 1 row, then that block will be rendered on the upper half of the column.\nAnd the bottom row of the column will remain empty.\n",
                                    "max_num": 2,
                                    "min_num": 1,
                                    "required": True,
                                },
                            ),
                            52: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 4), ("rows", 51)]],
                                {},
                            ),
                            53: (
                                "wagtail.blocks.StreamBlock",
                                [[("column", 52)]],
                                {
                                    "help_text": "\nAdd up to 5 number column components within this row. \nThe columns are ordered from left to right, top to bottom respectively. \nSo by moving 1 column component above the other, that component will be rendered in the column left of the other. \n",
                                    "max_num": 5,
                                    "min_num": 1,
                                },
                            ),
                            54: ("wagtail.blocks.StructBlock", [[("columns", 53)]], {}),
                            55: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "\nThe sub title to display for this component.\n",
                                    "required": True,
                                },
                            ),
                            56: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": cms.dynamic_content.cards.WHAlerts.get_alerts,
                                    "help_text": "\nThis is used to select the current weather health alert type Eg: Heat or Cold alert season.\n",
                                },
                            ),
                            57: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 4), ("sub_title", 55), ("alert_type", 56)]],
                                {},
                            ),
                            58: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("text_card", 3),
                                        ("chart_card_section", 50),
                                        ("headline_numbers_row_card", 54),
                                        ("weather_health_alert_card", 57),
                                    ]
                                ],
                                {
                                    "help_text": "\nHere you can add any number of content row cards for this section.\nNote that these cards will be displayed across the available width.\n"
                                },
                            ),
                            59: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("page_link", 1), ("content", 58)]],
                                {},
                            ),
                        },
                    ),
                ),
                ("sub_title", models.CharField(max_length=255)),
                (
                    "related_links_layout",
                    models.CharField(
                        choices=[("Sidebar", "Sidebar"), ("Footer", "Footer")],
                        default="Footer",
                        help_text="\nThis dictates where the related links for this page will be positioned.\n",
                        max_length=10,
                        verbose_name="Layout",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LandingPageRelatedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=400, verbose_name="URL")),
                ("body", wagtail.fields.RichTextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_links",
                        to="home.landingpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
