# Generated by Django 5.1.2 on 2024-10-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_homepage_body_alter_landingpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpage",
            name="related_links_layout",
        ),
        migrations.DeleteModel(
            name="LandingPageRelatedLink",
        ),
    ]
