# Generated by Django 5.1.6 on 2025-03-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_add_chart_y_axis_min_and_max"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagerelatedlink",
            name="page",
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
        migrations.DeleteModel(
            name="HomePageRelatedLink",
        ),
    ]
