# Generated by Django 5.1.7 on 2025-05-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_add_single_page_announcement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LandingPageAnnouncement",
        ),
    ]
