# Generated by Django 5.1.7 on 2025-04-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_alter_landingpageannouncement_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpageannouncement",
            name="badge",
        ),
    ]
