# Generated by Django 5.1.7 on 2025-05-07 12:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_delete_landingpageannouncement"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPageAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="\nThe title to associate with the announcement. This must be provided.\n",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        help_text="\nA body of text to be displayed by the announcement. There is a limit of 255 characters for this field.\n",
                        max_length=255,
                    ),
                ),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("Information", "Information"),
                            ("Warning", "Warning"),
                        ],
                        default="Information",
                        help_text="\nThe type to associate with the announcement. Defaults to `Information`.\n",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="\nWhether to activate this banner only on this individual page. \nNote that multiple page banners can be active on one page. Consider \ncarefully if you need multiple announcements to be active at once as\nthis can have an impact on user experience of the dashboard page.\n",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to="home.landingpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
