# Generated by Django 5.1.7 on 2025-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_remove_landingpageannouncement_badge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landingpageannouncement",
            options={"base_manager_name": "objects"},
        ),
    ]
