# Generated by Django 5.1.7 on 2025-05-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_alter_landingpageannouncement_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landingpageannouncement",
            options={},
        ),
    ]
