# Generated by Django 5.2.9 on 2026-02-25 12:31

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_alter_landingpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="page_description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="\nAn optional body of text which will be rendered at the top of the page. \nThis text will be displayed after the title of the page and before any of the main content.\n",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="related_links_layout",
            field=models.CharField(
                choices=[("Sidebar", "Sidebar"), ("Footer", "Footer")],
                default="Footer",
                help_text="\nThis dictates where the related links for this page will be positioned.\n",
                max_length=10,
                verbose_name="Layout",
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="sub_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="LandingPageRelatedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=400, verbose_name="URL")),
                ("body", wagtail.fields.RichTextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_links",
                        to="home.landingpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
