# Generated by Django 5.2.12 on 2026-03-13 10:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_alter_landingpage_body_date_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpagerelatedlink",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
