# Generated by Django 5.2.13 on 2026-05-07 09:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_alter_landingpage_body_headline_metric_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="health_topic",
            field=wagtail.fields.StreamField(
                [("health_topic", 2)],
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nThe text you add here will be used as the heading for this section. \n",
                            "required": True,
                        },
                    ),
                    1: (
                        "cms.dynamic_content.blocks.PageLinkChooserBlock",
                        (),
                        {
                            "help_text": "\nThe related topic page you want to link to. Eg: `COVID-19`\n",
                            "page_type": ["topics_list.TopicsListPage"],
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("page", 1)]],
                        {},
                    ),
                },
                default=list,
            ),
        ),
    ]
