# Generated by Django 5.1.7 on 2025-04-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_formpageannouncement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formpageannouncement",
            options={},
        ),
    ]
