# Generated by Django 5.1.7 on 2025-04-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_alter_formpageannouncement_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpageannouncement",
            name="badge",
        ),
    ]
