# Generated by Django 5.1.7 on 2025-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_remove_formpageannouncement_badge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formpageannouncement",
            options={"base_manager_name": "objects"},
        ),
    ]
