# Generated by Django 4.2.6 on 2023-10-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whats_new", "0001_add_badge_whats_new_parent_and_child_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="colour",
            field=models.CharField(
                choices=[
                    ("GREY", "Grey"),
                    ("GREEN", "Green"),
                    ("TURQUOISE", "Turquoise"),
                    ("BLUE", "Blue"),
                    ("PURPLE", "Purple"),
                    ("PINK", "Pink"),
                    ("RED", "Red"),
                    ("ORANGE", "Orange"),
                    ("YELLOW", "Yellow"),
                ],
                default="GREY",
                max_length=20,
            ),
        ),
    ]
