# Generated by Django 5.0.6 on 2024-07-05 15:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "whats_new",
            "0002_add_seo_change_frequency_and_priority_fields_to_parent_and_child_pages",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsnewchildentry",
            name="page_description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
