# Generated by Django 5.1.2 on 2024-11-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whats_new", "0005_add_pagination_control_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsnewparentpage",
            name="related_links_layout",
        ),
        migrations.DeleteModel(
            name="WhatsNewParentPageRelatedLink",
        ),
    ]
