# Generated by Django 5.1.7 on 2025-05-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whats_new", "0007_add_single_page_announcement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsnewparentpageannouncement",
            name="page",
        ),
        migrations.DeleteModel(
            name="WhatsNewChildEntryAnnouncement",
        ),
        migrations.DeleteModel(
            name="WhatsNewParentPageAnnouncement",
        ),
    ]
