# Generated by Django 5.1.7 on 2025-04-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whats_new", "0009_alter_whatsnewchildentryannouncement_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsnewchildentryannouncement",
            name="badge",
        ),
        migrations.RemoveField(
            model_name="whatsnewparentpageannouncement",
            name="badge",
        ),
    ]
