# Generated by Django 5.1.7 on 2025-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whats_new", "0010_remove_whatsnewchildentryannouncement_badge_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whatsnewchildentryannouncement",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="whatsnewparentpageannouncement",
            options={"base_manager_name": "objects"},
        ),
    ]
