# Generated by Django 5.1.7 on 2025-05-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whats_new", "0011_alter_whatsnewchildentryannouncement_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whatsnewchildentryannouncement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="whatsnewparentpageannouncement",
            options={},
        ),
    ]
