name: 'Venv Cache'

description: 'Read / write the virtual environment cache'

runs:
  using: 'composite'
  steps:
    - name: Cache virtual environment
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          .venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
