# Generated by Django 5.0.2 on 2024-03-01 13:57

import cms.snippets.models.external_button
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_download_button_snippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                (
                    "button_type",
                    models.CharField(
                        choices=[
                            ("Primary", "Primary"),
                            ("Secondary", "Secondary"),
                            ("Warning", "Warning"),
                        ],
                        default="Primary",
                        help_text="\nA required choice of what type of button you want, the options include `Primary`, `Secondary`.\nThese align with GDS guidelines.\n",
                        max_length=255,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Download", "Download"),
                            ("Start", "Start"),
                        ],
                        default="None",
                        help_text="\nA required choice of icon to add to a button, defaults to none.\n",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
