# Generated by Django 5.0.3 on 2024-03-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "snippets",
            "0004_alter_externalbutton_button_type_and_icon_choices_implementation",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "button_type",
                    models.CharField(
                        choices=[("BULK_DOWNLOAD", "BULK_DOWNLOAD")],
                        default="BULK_DOWNLOAD",
                        max_length=25,
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
