# Generated by Django 5.0.4 on 2024-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0007_add_global_banner_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Button",
        ),
        migrations.AlterField(
            model_name="internalbutton",
            name="button_type",
            field=models.CharField(
                choices=[("BULK_DOWNLOAD", "Bulk Download")],
                default="BULK_DOWNLOAD",
                max_length=25,
            ),
        ),
    ]
