# Generated by Django 5.0.4 on 2024-06-18 10:02

import cms.metrics_interface.field_choices_callables
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0008_delete_button_alter_internalbutton_button_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherAlertButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "button_type",
                    models.CharField(
                        choices=[("Heat", "Heat"), ("Cold", "Cold")],
                        default="Heat",
                        max_length=25,
                    ),
                ),
                (
                    "geography_code",
                    models.CharField(
                        blank=True,
                        choices=cms.metrics_interface.field_choices_callables.get_all_geography_names_and_codes_for_alerts,
                        max_length=9,
                    ),
                ),
            ],
        ),
    ]
