# Generated by Django 5.1.7 on 2025-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0010_add_menu_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalbanner",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="globalbanner",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="globalbanner",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="\nWhether to activate this banner across every page in the dashboard. \nMultiple banners can be active across the dashboard.\nNote: Warning banners are prioritised across the dashboard and will be displayed above information banners.\n",
            ),
        ),
    ]
