# Generated by Django 5.2.7 on 2025-11-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0012_alter_globalbanner_timestamps_to_prevent_null_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatheralertbutton",
            name="geography_code",
        ),
    ]
