# Generated by Django 5.2.4 on 2025-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0012_alter_globalbanner_timestamps_to_prevent_null_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccreditationBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accreditation_type",
                    models.CharField(
                        choices=[
                            ("Official", "Official"),
                            ("Official Accredited", "Official Accredited"),
                            ("Experimental", "Experimental"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
    ]
