# Generated by Django 5.2.11 on 2026-03-19 14:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0013_remove_geography_code_field_from_wha_button"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_label",
                    models.TextField(
                        help_text="\nA label to associate with this particular menu design.\nNote that this label is private / internal and is not used on the dashboard.\nThis is purely to help identify each of the constructed menu designs.\n"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="\nWhether to activate this menu. \nNote that only 1 menu can be active at a time.\nTo switch from 1 active menu to another, \nyou must deactivate the 1st menu and save it before activating and saving the 2nd menu.\n",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "\nThe title to display for this menu item.\nAs a general rule of thumb, the title length should be no longer than 60 characters.\n",
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                ("wagtailcore.Page",),
                                {
                                    "on_delete": django.db.models.deletion.CASCADE,
                                    "related_name": "+",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1)]],
                                {},
                            ),
                        },
                        help_text="\nThe menu is constructed from a grid system of rows and columns.\nThere can be any number of rows and columns.\nBut each column should have at least 1 link.\n",
                    ),
                ),
            ],
        ),
    ]
