# Generated by Django 5.2.13 on 2026-05-07 09:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0014_simplemenu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplemenu",
            name="body",
            field=wagtail.fields.StreamField(
                [("link", 2)],
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nThe title to display for this menu item.\nAs a general rule of thumb, the title length should be no longer than 60 characters.\n",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        ("wagtailcore.Page",),
                        {
                            "on_delete": django.db.models.deletion.CASCADE,
                            "related_name": "+",
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("page", 1)]],
                        {},
                    ),
                },
                help_text="\nLinks to display in the menu.\n",
            ),
        ),
    ]
