# Generated by Django 5.2.13 on 2026-06-02 15:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0015_alter_simplemenu_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="body",
            field=wagtail.fields.StreamField(
                [("row", 11)],
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nAn optional heading to place at the top of this menu column.\n",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "\nThe title to display for this menu item.\nAs a general rule of thumb, the title length should be no longer than 60 characters.\n",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "\nAn optional body of text to display for this menu item.\n",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        ("wagtailcore.Page",),
                        {
                            "on_delete": django.db.models.deletion.CASCADE,
                            "related_name": "+",
                        },
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "\nOnly public pages can be displayed in the menu. Please tick this box to confirm the page you are adding is public.\n",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("body", 2),
                                ("page", 3),
                                ("is_page_public", 4),
                            ]
                        ],
                        {"required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("body", 2),
                                ("page", 3),
                                ("is_page_public", 4),
                            ]
                        ],
                        {
                            "help_text": "\nA secondary link to attach to the list of submenu items under the primary menu link.\n",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("secondary_link", 6)]],
                        {
                            "help_text": "\nOptional secondary / submenu links to attach under the primary menu link.\n",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("primary_link", 5), ("secondary_links", 7)]],
                        {
                            "help_text": "\nAdd any number of associated links within this menu column.\n"
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("links", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("column", 9)]],
                        {
                            "help_text": "\nAdd any number of columns within this menu row.\n"
                        },
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("columns", 10)]], {}),
                },
                help_text="\nThe menu is constructed from a grid system of rows and columns.\nThere can be any number of rows and columns.\nBut each column should have at least 1 link.\n",
            ),
        ),
    ]
