# Generated by Django 4.2.7 on 2024-01-09 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0001_initial"),
        ("common", "0002_increase_url_field_length_commonpage_related_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonpage",
            name="button",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="snippets.button",
            ),
        ),
    ]
