# Generated by Django 5.0.4 on 2024-06-26 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_increase_url_field_length_commonpage_related_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonpage",
            name="seo_change_frequency",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Always"),
                    (2, "Hourly"),
                    (3, "Daily"),
                    (4, "Weekly"),
                    (5, "Monthly"),
                    (6, "Yearly"),
                    (7, "Never"),
                ],
                help_text="<p>This value tells search engines how often a page’s content updates, offering a hint for crawling prioritization.</p>\n<p><strong>Always</strong>: This means the page is constantly changing with important, up-to-the-minute updates. A subreddit index page, a stock market data page, and the index page of a major news site might use this tag.</p>\n<p><strong>Hourly</strong>: The page is updated on an hourly basis or thereabouts. Major news sites, weather sites, and active web forums might use this tag.</p>\n<p><strong>Daily</strong>: The page is updated with new content on average once a day. Small web forums, classified ad pages, daily newspapers, and daily blogs might use this tag for their homepage.</p>\n<p><strong>Weekly</strong>: The page is updated around once a week with new content. Product info pages with daily pricing information, small blogs, and website directories use this tag.</p>\n<p><strong>Monthly</strong>: The page is updated around once a month; maybe more, maybe less. Category pages, evergreen guides with updated information, and FAQs often use this tag.</p>\n<p><strong>Yearly</strong>: The page is rarely updated but may receive updates once or twice a year. Many static pages, such as registration pages, About pages, and privacy policies, fall into this category.</p>\n<p><strong>Never</strong>: The page is never going to be updated. Old blog entries, old news stories, and completely static pages fall into this category. </p>",
                null=True,
                verbose_name="SEO change frequency",
            ),
        ),
        migrations.AddField(
            model_name="commonpage",
            name="seo_priority",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="\nThis value signals the importance of a page to search engines. \nAssigning accurate priority values to key pages of your site can help search engines understand \nthe structure and hierarchy of your content.\nThis must be a number between 0.1 - 1.0.\n",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1.0),
                    django.core.validators.MinValueValidator(0.099),
                ],
                verbose_name="SEO priority",
            ),
        ),
    ]
