# Generated by Django 5.1.2 on 2024-11-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_add_related_links_layout_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commonpage",
            name="date_posted",
        ),
    ]
