# Generated by Django 5.1.7 on 2025-03-25 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_commonpageannouncement"),
        (
            "whats_new",
            "0006_remove_whatsnewparentpage_related_links_layout_and_related_links",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="commonpageannouncement",
            name="badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="whats_new.badge",
            ),
        ),
    ]
