# Generated by Django 5.1.7 on 2025-05-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_compositepageannouncement"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompositePageAnnouncement",
            new_name="CommonPageAnnouncement",
        ),
    ]
