# Generated by Django 5.1.7 on 2025-04-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_alter_commonpageannouncement_banner_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonpageannouncement",
            options={},
        ),
    ]
