# Generated by Django 5.1.7 on 2025-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_remove_commonpageannouncement_badge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonpageannouncement",
            options={"base_manager_name": "objects"},
        ),
    ]
