# Generated by Django 5.1.7 on 2025-05-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_commonpageannouncement_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonpageannouncement",
            options={},
        ),
    ]
