# Generated by Django 4.2.7 on 2023-12-12 13:48
import datetime
from django.db import migrations


def load_data(apps, schema_edior):
    metrics_docs_parent = apps.get_model("metrics_documentation", "MetricsDocumentationParentPage")
    print(metrics_docs_parent)
    metrics_docs_parent(
        title="metrics documentation",
        depth=1,
        date_posted=datetime.datetime.today(),
        body=(
            "<p data-block-key=\"wk1ht\">"
            "Here we outline a list of metrics available in the UKHSA"
            "data dashboard. Click to view more information about a metric"
            "</p>",
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("metrics_documentation", "0002_metricsdocumentationchildentry"),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
